;; wc.wat — counts bytes and newlines in stdin, prints "<lines> <bytes>\n".
(module
  (import "wasi_snapshot_preview1" "fd_read"
    (func $fd_read (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_write"
    (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "proc_exit"
    (func $proc_exit (param i32)))
  (memory (export "memory") 1)

  (func $itoa (param $n i32) (param $buf i32) (result i32)
    (local $len i32) (local $i i32) (local $j i32) (local $tmp i32)
    (if (i32.eqz (local.get $n))
      (then (i32.store8 (local.get $buf) (i32.const 48))
            (return (i32.const 1))))
    (local.set $len (i32.const 0))
    (block $d (loop $L
      (br_if $d (i32.eqz (local.get $n)))
      (i32.store8 (i32.add (local.get $buf) (local.get $len))
        (i32.add (i32.const 48) (i32.rem_u (local.get $n) (i32.const 10))))
      (local.set $n (i32.div_u (local.get $n) (i32.const 10)))
      (local.set $len (i32.add (local.get $len) (i32.const 1)))
      (br $L)))
    (local.set $i (i32.const 0))
    (local.set $j (i32.sub (local.get $len) (i32.const 1)))
    (block $rd (loop $R
      (br_if $rd (i32.ge_s (local.get $i) (local.get $j)))
      (local.set $tmp (i32.load8_u (i32.add (local.get $buf) (local.get $i))))
      (i32.store8 (i32.add (local.get $buf) (local.get $i))
        (i32.load8_u (i32.add (local.get $buf) (local.get $j))))
      (i32.store8 (i32.add (local.get $buf) (local.get $j)) (local.get $tmp))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (local.set $j (i32.sub (local.get $j) (i32.const 1)))
      (br $R)))
    (local.get $len))

  (func $_start (export "_start")
    (local $n i32) (local $i i32) (local $bytes i32) (local $lines i32)
    (local $off i32) (local $len i32)
    (local.set $bytes (i32.const 0))
    (local.set $lines (i32.const 0))
    (block $eof (loop $L
      (i32.store (i32.const 0) (i32.const 4096))
      (i32.store (i32.const 4) (i32.const 4096))
      (drop (call $fd_read (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 8)))
      (local.set $n (i32.load (i32.const 8)))
      (br_if $eof (i32.eqz (local.get $n)))
      (local.set $bytes (i32.add (local.get $bytes) (local.get $n)))
      (local.set $i (i32.const 0))
      (block $cd (loop $C
        (br_if $cd (i32.ge_s (local.get $i) (local.get $n)))
        (if (i32.eq (i32.load8_u (i32.add (i32.const 4096) (local.get $i)))
                    (i32.const 10))
          (then (local.set $lines (i32.add (local.get $lines) (i32.const 1)))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $C)))
      (br $L)))
    ;; Format: "<lines> <bytes>\n" at offset 32.
    (local.set $off (i32.const 32))
    (local.set $len (call $itoa (local.get $lines) (local.get $off)))
    (local.set $off (i32.add (local.get $off) (local.get $len)))
    (i32.store8 (local.get $off) (i32.const 32))
    (local.set $off (i32.add (local.get $off) (i32.const 1)))
    (local.set $len (call $itoa (local.get $bytes) (local.get $off)))
    (local.set $off (i32.add (local.get $off) (local.get $len)))
    (i32.store8 (local.get $off) (i32.const 10))
    (local.set $off (i32.add (local.get $off) (i32.const 1)))
    (i32.store (i32.const 0) (i32.const 32))
    (i32.store (i32.const 4) (i32.sub (local.get $off) (i32.const 32)))
    (drop (call $fd_write (i32.const 1) (i32.const 0) (i32.const 1) (i32.const 12)))
    (call $proc_exit (i32.const 0))
  )
)
