/*
 * arch/x86/kernel/tls13_server.c — TLS 1.3 server-side handshake
 * (RFC 8446).  Sister to tls13.c (the client).  Self-contained
 * session state (srv13) so the two can coexist in the same kernel.
 *
 * Cipher suite: AES_128_GCM_SHA256 (0x1301).
 * Group:        x25519.
 * Server auth:  ECDSA P-256 SHA-256 over the transcript per §4.4.3.
 *
 * Cert + key are loaded from osfs2 at server-start time:
 *   cluster/tls-cert.der  - DER-encoded leaf certificate
 *   cluster/tls-key.bin   - 32-byte big-endian P-256 private key
 *
 * Either is generated by the host-side script
 * tools/cluster-gen-cert.sh once and persisted in nvme.img.
 */
#include "../include/types.h"

extern void serial_puts(const char *s);
extern void serial_putdec(uint64_t v);

/* Crypto primitives — same set tls13.c uses. */
extern void x25519(uint8_t out[32], const uint8_t scalar[32], const uint8_t point[32]);
extern void x25519_public(uint8_t pub[32], const uint8_t priv[32]);
extern void sha256(const uint8_t *data, uint32_t len, uint8_t hash[32]);
extern void hmac_sha256(const uint8_t *key, uint32_t key_len,
                         const uint8_t *data, uint32_t data_len,
                         uint8_t out[32]);
extern void hkdf_extract(const uint8_t *salt, uint32_t salt_len,
                          const uint8_t *ikm, uint32_t ikm_len, uint8_t prk[32]);
extern void hkdf_expand_label(const uint8_t prk[32], const char *label,
                                const uint8_t *context, uint32_t context_len,
                                uint8_t *okm, uint32_t okm_len);
extern int  aes128_gcm_encrypt(const uint8_t key[16], const uint8_t iv[12],
                                const void *aad, uint32_t aad_len,
                                const void *pt, uint32_t pt_len,
                                void *ct, uint8_t tag[16]);
extern int  aes128_gcm_decrypt(const uint8_t key[16], const uint8_t iv[12],
                                const void *aad, uint32_t aad_len,
                                const void *ct, uint32_t ct_len,
                                void *pt, const uint8_t tag[16]);
extern void random_get_bytes(void *buf, uint32_t len);
extern int  ecdsa_p256_sign(const uint8_t d_be[32], const uint8_t hash[32],
                             uint8_t *sig_out, uint32_t sig_cap);

/* Net + fs. */
extern int  net_tcp_send(int conn, const void *data, uint32_t len);
extern int  net_tcp_recv_timeout(int conn, void *buf, uint32_t size, uint32_t to);
extern int  net_tcp_listen(uint16_t port);
extern int  net_tcp_accept(int listener, uint32_t timeout_ticks);
extern void net_tcp_close(int conn);
extern bool vfs_find(const char *path, int mode, void *out_node);
extern int  vfs_read(void *node, uint64_t offset, void *buf, uint64_t len);
extern int  kthread_create(const char *name, void (*fn)(void *), void *data);
extern void sched_yield(void);

/* ── Constants ──────────────────────────────────────────────── */

#define TLS_CONTENT_HANDSHAKE     22
#define TLS_CONTENT_APP_DATA      23
#define TLS_CONTENT_CHANGE_CIPHER 20
#define TLS_CONTENT_ALERT         21

#define HS_CLIENT_HELLO      1
#define HS_SERVER_HELLO      2
#define HS_NEW_SESS_TKT      4
#define HS_ENCRYPTED_EXT     8
#define HS_CERTIFICATE      11
#define HS_CERT_VERIFY      15
#define HS_FINISHED         20

#define AES_128_GCM_SHA256  0x1301
#define EXT_SUPPORTED_VERSIONS  43
#define EXT_KEY_SHARE           51
#define EXT_SUPPORTED_GROUPS    10
#define EXT_SIG_ALGS            13
#define EXT_SERVER_NAME          0
#define GROUP_X25519     0x001D
#define SIG_ECDSA_P256_SHA256  0x0403

#define SRV_TRANSCRIPT_MAX 16384

typedef struct {
    int      tcp_conn;
    bool     active;

    uint8_t  client_random[32];
    uint8_t  server_random[32];
    uint8_t  client_pub[32];     /* peer's x25519 share */
    uint8_t  server_priv[32];
    uint8_t  server_pub[32];
    uint8_t  shared[32];

    uint8_t  handshake_secret[32];
    uint8_t  c_hs_traffic[32];
    uint8_t  s_hs_traffic[32];
    uint8_t  c_ap_traffic[32];
    uint8_t  s_ap_traffic[32];

    uint8_t  c_hs_key[16]; uint8_t  c_hs_iv[12];
    uint8_t  s_hs_key[16]; uint8_t  s_hs_iv[12];
    uint8_t  c_ap_key[16]; uint8_t  c_ap_iv[12];
    uint8_t  s_ap_key[16]; uint8_t  s_ap_iv[12];
    uint64_t c_seq, s_seq;

    uint8_t  transcript[SRV_TRANSCRIPT_MAX];
    uint32_t transcript_len;

    uint8_t  rec_hdr[5];     /* last read record header for AEAD AAD */

    /* legacy_session_id from ClientHello — RFC 8446 §4.1.3 requires
     * the server to echo it verbatim in ServerHello. */
    uint8_t  ch_session_id[32];
    uint8_t  ch_session_id_len;
} srv13_session_t;

static srv13_session_t srv13;
static const uint8_t   zero32[32] = {0};

/* Server identity, populated at start time. */
static uint8_t  srv_cert_der[4096];
static uint32_t srv_cert_der_len;
static uint8_t  srv_priv_be[32];
static bool     srv_identity_loaded = false;

/* ── Small helpers ──────────────────────────────────────────── */

static void s_memcpy(void *d, const void *s, uint32_t n)
{ uint8_t *D=d; const uint8_t *S=s; for (uint32_t i=0;i<n;i++) D[i]=S[i]; }
static void s_memset(void *d, int v, uint32_t n)
{ uint8_t *D=d; for (uint32_t i=0;i<n;i++) D[i]=(uint8_t)v; }
static int s_memeq_ct(const uint8_t *a, const uint8_t *b, uint32_t n)
{ uint8_t d=0; for (uint32_t i=0;i<n;i++) d|=a[i]^b[i]; return d==0; }

static void th_append(const uint8_t *msg, uint32_t len)
{
    if (srv13.transcript_len + len > SRV_TRANSCRIPT_MAX) return;
    s_memcpy(srv13.transcript + srv13.transcript_len, msg, len);
    srv13.transcript_len += len;
}
static void th_compute(uint8_t out[32])
{ sha256(srv13.transcript, srv13.transcript_len, out); }

static void derive_key_iv(const uint8_t secret[32],
                           uint8_t key_out[16], uint8_t iv_out[12])
{
    hkdf_expand_label(secret, "key", 0, 0, key_out, 16);
    hkdf_expand_label(secret, "iv",  0, 0, iv_out,  12);
}

static void make_nonce(uint8_t nonce[12], const uint8_t iv[12], uint64_t seq)
{
    for (int i = 0; i < 12; i++) nonce[i] = iv[i];
    for (int i = 0; i < 8; i++) nonce[11 - i] ^= (uint8_t)(seq >> (i * 8));
}

/* ── Record I/O ─────────────────────────────────────────────── */

static int read_record(int conn, uint8_t *type_out,
                        uint8_t *body, uint32_t cap, uint32_t *body_len_out)
{
    uint32_t got = 0;
    uint8_t hdr[5];
    while (got < 5) {
        int n = net_tcp_recv_timeout(conn, hdr + got, 5 - got, 500);
        if (n <= 0) return -1;
        got += (uint32_t)n;
    }
    uint16_t rec_len = ((uint16_t)hdr[3] << 8) | hdr[4];
    if (rec_len > cap) return -1;
    got = 0;
    while (got < rec_len) {
        int n = net_tcp_recv_timeout(conn, body + got, rec_len - got, 500);
        if (n <= 0) return -1;
        got += (uint32_t)n;
    }
    if (type_out)     *type_out = hdr[0];
    if (body_len_out) *body_len_out = rec_len;
    s_memcpy(srv13.rec_hdr, hdr, 5);
    return 0;
}

static int decrypt_record(uint8_t *body, uint32_t body_len,
                           const uint8_t key[16], const uint8_t iv[12],
                           uint64_t seq, uint8_t *inner_type, uint32_t *pt_len)
{
    if (body_len < 17) return -1;
    uint8_t nonce[12]; make_nonce(nonce, iv, seq);
    uint8_t aad[5]; s_memcpy(aad, srv13.rec_hdr, 5);
    uint32_t ct_len = body_len - 16;
    const uint8_t *tag = body + ct_len;
    static uint8_t pt_scratch[17000];
    if (ct_len > sizeof pt_scratch) return -1;
    int r = aes128_gcm_decrypt(key, nonce, aad, 5, body, ct_len, pt_scratch, tag);
    if (r != 0) return -1;
    s_memcpy(body, pt_scratch, ct_len);
    uint32_t end = ct_len;
    while (end > 0 && body[end - 1] == 0) end--;
    if (end == 0) return -1;
    *inner_type = body[end - 1];
    *pt_len = end - 1;
    return 0;
}

static int send_encrypted(int conn, uint8_t inner_type,
                           const uint8_t *pt, uint32_t pt_len,
                           const uint8_t key[16], const uint8_t iv[12],
                           uint64_t seq)
{
    static uint8_t scratch[17000];
    if (pt_len + 1 + 16 + 5 > sizeof scratch) return -1;
    s_memcpy(scratch + 5, pt, pt_len);
    scratch[5 + pt_len] = inner_type;
    uint32_t inner_len = pt_len + 1;
    uint32_t ct_len = inner_len + 16;
    scratch[0] = TLS_CONTENT_APP_DATA;
    scratch[1] = 0x03; scratch[2] = 0x03;
    scratch[3] = (uint8_t)(ct_len >> 8);
    scratch[4] = (uint8_t)ct_len;
    uint8_t nonce[12]; make_nonce(nonce, iv, seq);
    uint8_t tag[16];
    aes128_gcm_encrypt(key, nonce, scratch, 5,
                        scratch + 5, inner_len, scratch + 5, tag);
    s_memcpy(scratch + 5 + inner_len, tag, 16);
    return net_tcp_send(conn, scratch, 5 + ct_len);
}

/* Send a plaintext handshake record (used for ClientHello/ServerHello). */
static int send_plain_handshake(int conn, const uint8_t *body, uint32_t body_len)
{
    uint8_t hdr[5];
    hdr[0] = TLS_CONTENT_HANDSHAKE;
    hdr[1] = 0x03; hdr[2] = 0x03;
    hdr[3] = (uint8_t)(body_len >> 8);
    hdr[4] = (uint8_t)body_len;
    if (net_tcp_send(conn, hdr, 5) < 0) return -1;
    if (net_tcp_send(conn, body, body_len) < 0) return -1;
    return 0;
}

/* ── Parse ClientHello + extract client_pub + client_random ─── */

static int parse_client_hello(const uint8_t *body, uint32_t len)
{
    if (len < 4) return -1;
    if (body[0] != HS_CLIENT_HELLO) return -1;
    uint32_t hs_len = ((uint32_t)body[1] << 16) | ((uint32_t)body[2] << 8) | body[3];
    if (4 + hs_len > len) return -1;
    /* legacy_version(2) + random(32) */
    if (4 + 2 + 32 > len) return -1;
    s_memcpy(srv13.client_random, body + 4 + 2, 32);
    uint32_t off = 4 + 2 + 32;
    if (off + 1 > len) return -1;
    uint8_t sid_len = body[off++];
    if (sid_len > 32 || off + sid_len > len) return -1;
    /* Capture for ServerHello echo per RFC 8446 §4.1.3. */
    srv13.ch_session_id_len = sid_len;
    if (sid_len) s_memcpy(srv13.ch_session_id, body + off, sid_len);
    off += sid_len;
    if (off + 2 > len) return -1;
    /* cipher_suites */
    uint16_t cs_len = ((uint16_t)body[off] << 8) | body[off + 1];
    off += 2;
    bool ok_suite = false;
    for (uint32_t i = 0; i + 1 < cs_len; i += 2) {
        uint16_t c = ((uint16_t)body[off + i] << 8) | body[off + i + 1];
        if (c == AES_128_GCM_SHA256) ok_suite = true;
    }
    off += cs_len;
    if (!ok_suite) {
        serial_puts("[TLS1.3-S] client doesn't offer AES_128_GCM_SHA256\n");
        return -1;
    }
    /* legacy_compression_methods (1 byte len + content) */
    if (off + 1 > len) return -1;
    uint8_t cm_len = body[off++];
    off += cm_len;
    /* extensions */
    if (off + 2 > len) return -1;
    uint16_t ext_total = ((uint16_t)body[off] << 8) | body[off + 1];
    off += 2;
    if (off + ext_total > len) return -1;
    bool got_version = false, got_ks = false;
    uint32_t ext_end = off + ext_total;
    while (off + 4 <= ext_end) {
        uint16_t et  = ((uint16_t)body[off] << 8) | body[off + 1];
        uint16_t el  = ((uint16_t)body[off + 2] << 8) | body[off + 3];
        off += 4;
        if (off + el > ext_end) return -1;
        if (et == EXT_SUPPORTED_VERSIONS) {
            /* client form: 1-byte list_len + repeated u16 versions */
            if (el < 1) return -1;
            uint8_t lst = body[off];
            for (uint32_t i = 0; i + 1 < lst; i += 2) {
                uint16_t v = ((uint16_t)body[off + 1 + i] << 8) | body[off + 1 + i + 1];
                if (v == 0x0304) got_version = true;
            }
        } else if (et == EXT_KEY_SHARE) {
            /* client form: 2-byte list_len, then repeated (group(2) + key_len(2) + key) */
            if (el < 2) return -1;
            uint16_t list_len = ((uint16_t)body[off] << 8) | body[off + 1];
            uint32_t p = off + 2;
            uint32_t list_end = off + 2 + list_len;
            if (list_end > off + el) return -1;
            while (p + 4 <= list_end) {
                uint16_t g  = ((uint16_t)body[p] << 8) | body[p + 1];
                uint16_t kl = ((uint16_t)body[p + 2] << 8) | body[p + 3];
                p += 4;
                if (p + kl > list_end) break;
                if (g == GROUP_X25519 && kl == 32) {
                    s_memcpy(srv13.client_pub, body + p, 32);
                    got_ks = true;
                }
                p += kl;
            }
        }
        off += el;
    }
    if (!got_version) { serial_puts("[TLS1.3-S] no TLS 1.3 in CH\n"); return -1; }
    if (!got_ks)      { serial_puts("[TLS1.3-S] no x25519 share in CH\n"); return -1; }
    return 0;
}

/* ── Build ServerHello ──────────────────────────────────────── */

static int build_server_hello(uint8_t *buf, uint32_t cap)
{
    if (cap < 128) return -1;
    int p = 0;
    buf[p++] = HS_SERVER_HELLO;
    int hs_len_pos = p; p += 3;
    int hs_body_start = p;

    buf[p++] = 0x03; buf[p++] = 0x03;                 /* legacy_version */
    s_memcpy(buf + p, srv13.server_random, 32); p += 32;
    /* legacy_session_id_echo: verbatim copy of CH session_id per
     * RFC 8446 §4.1.3.  openssl s_client uses a non-empty session_id
     * for middlebox-compat; an empty echo here trips its validation. */
    buf[p++] = srv13.ch_session_id_len;
    if (srv13.ch_session_id_len) {
        s_memcpy(buf + p, srv13.ch_session_id, srv13.ch_session_id_len);
        p += srv13.ch_session_id_len;
    }
    buf[p++] = 0x13; buf[p++] = 0x01;                 /* cipher_suite = AES_128_GCM_SHA256 */
    buf[p++] = 0;                                     /* legacy_compression_method */

    int ext_len_pos = p; p += 2;
    int ext_start = p;

    /* supported_versions extension — TLS 1.3 */
    buf[p++] = 0x00; buf[p++] = EXT_SUPPORTED_VERSIONS;
    buf[p++] = 0x00; buf[p++] = 0x02;
    buf[p++] = 0x03; buf[p++] = 0x04;

    /* key_share extension — server's x25519 public key */
    buf[p++] = 0x00; buf[p++] = EXT_KEY_SHARE;
    buf[p++] = 0x00; buf[p++] = 0x24;                 /* ext len 36 */
    buf[p++] = 0x00; buf[p++] = 0x1D;                 /* group x25519 */
    buf[p++] = 0x00; buf[p++] = 0x20;                 /* key len 32 */
    s_memcpy(buf + p, srv13.server_pub, 32); p += 32;

    uint16_t el = (uint16_t)(p - ext_start);
    buf[ext_len_pos]     = (uint8_t)(el >> 8);
    buf[ext_len_pos + 1] = (uint8_t)el;

    uint32_t hl = (uint32_t)(p - hs_body_start);
    buf[hs_len_pos]     = (uint8_t)(hl >> 16);
    buf[hs_len_pos + 1] = (uint8_t)(hl >> 8);
    buf[hs_len_pos + 2] = (uint8_t)hl;
    return p;
}

/* ── Build EncryptedExtensions (empty) ──────────────────────── */

static int build_encrypted_extensions(uint8_t *buf)
{
    int p = 0;
    buf[p++] = HS_ENCRYPTED_EXT;
    buf[p++] = 0; buf[p++] = 0; buf[p++] = 2;        /* hs_len = 2 */
    buf[p++] = 0; buf[p++] = 0;                       /* ext list len = 0 */
    return p;
}

/* ── Build Certificate message ──────────────────────────────── */

static int build_certificate(uint8_t *buf, uint32_t cap)
{
    if (cap < srv_cert_der_len + 16) return -1;
    int p = 0;
    buf[p++] = HS_CERTIFICATE;
    int hs_len_pos = p; p += 3;
    int hs_body_start = p;
    buf[p++] = 0;                                     /* cert_request_context: empty */
    /* cert_list u24 length */
    uint32_t entry_len = 3 + srv_cert_der_len + 2;    /* certlen + cert + ext_len */
    buf[p++] = (uint8_t)(entry_len >> 16);
    buf[p++] = (uint8_t)(entry_len >> 8);
    buf[p++] = (uint8_t)entry_len;
    /* entry: cert_len u24 || cert || extensions u16 (empty) */
    buf[p++] = (uint8_t)(srv_cert_der_len >> 16);
    buf[p++] = (uint8_t)(srv_cert_der_len >> 8);
    buf[p++] = (uint8_t)srv_cert_der_len;
    s_memcpy(buf + p, srv_cert_der, srv_cert_der_len);
    p += srv_cert_der_len;
    buf[p++] = 0; buf[p++] = 0;                       /* exts empty */
    uint32_t hl = (uint32_t)(p - hs_body_start);
    buf[hs_len_pos]     = (uint8_t)(hl >> 16);
    buf[hs_len_pos + 1] = (uint8_t)(hl >> 8);
    buf[hs_len_pos + 2] = (uint8_t)hl;
    return p;
}

/* ── Build CertificateVerify (ECDSA-P256-SHA256 over transcript) ─ */

static int build_certificate_verify(uint8_t *buf, uint32_t cap)
{
    if (cap < 128) return -1;
    /* signature_input = 64x 0x20 || "TLS 1.3, server CertificateVerify"
     *                   || 0x00 || transcript_hash */
    uint8_t sig_input[64 + 33 + 1 + 32];
    for (int i = 0; i < 64; i++) sig_input[i] = 0x20;
    const char *ctx = "TLS 1.3, server CertificateVerify";
    int ci = 0; while (ctx[ci]) { sig_input[64 + ci] = (uint8_t)ctx[ci]; ci++; }
    sig_input[64 + ci] = 0x00;
    uint8_t th[32]; th_compute(th);
    s_memcpy(sig_input + 64 + ci + 1, th, 32);
    uint32_t sig_input_len = 64 + (uint32_t)ci + 1 + 32;
    uint8_t digest[32];
    sha256(sig_input, sig_input_len, digest);
    uint8_t sig_der[80];
    int sl = ecdsa_p256_sign(srv_priv_be, digest, sig_der, sizeof sig_der);
    if (sl < 0) {
        serial_puts("[TLS1.3-S] ECDSA sign failed\n");
        return -1;
    }

    int p = 0;
    buf[p++] = HS_CERT_VERIFY;
    int hs_len_pos = p; p += 3;
    int hs_body_start = p;
    buf[p++] = (uint8_t)(SIG_ECDSA_P256_SHA256 >> 8);
    buf[p++] = (uint8_t)SIG_ECDSA_P256_SHA256;
    buf[p++] = (uint8_t)(sl >> 8);
    buf[p++] = (uint8_t)sl;
    s_memcpy(buf + p, sig_der, (uint32_t)sl);
    p += sl;
    uint32_t hl = (uint32_t)(p - hs_body_start);
    buf[hs_len_pos]     = (uint8_t)(hl >> 16);
    buf[hs_len_pos + 1] = (uint8_t)(hl >> 8);
    buf[hs_len_pos + 2] = (uint8_t)hl;
    return p;
}

/* ── Build server Finished ──────────────────────────────────── */

static int build_server_finished(uint8_t *buf)
{
    uint8_t th[32]; th_compute(th);
    uint8_t fk[32];
    hkdf_expand_label(srv13.s_hs_traffic, "finished", 0, 0, fk, 32);
    uint8_t mac[32];
    hmac_sha256(fk, 32, th, 32, mac);
    int p = 0;
    buf[p++] = HS_FINISHED;
    buf[p++] = 0; buf[p++] = 0; buf[p++] = 32;
    s_memcpy(buf + p, mac, 32); p += 32;
    return p;
}

/* ── Public: load cert+key from osfs2 ───────────────────────── */

int tls13_server_load_identity(void)
{
    static char node_buf[64];
    if (!vfs_find("cluster/tls-cert.der", 0, node_buf)) {
        serial_puts("[TLS1.3-S] no cluster/tls-cert.der on osfs2\n");
        return -1;
    }
    typedef struct { int v; uint32_t ino; void *data; uint64_t size; } node_t;
    node_t *n = (node_t *)node_buf;
    uint64_t want = n->size < sizeof srv_cert_der ? n->size : sizeof srv_cert_der;
    if (vfs_read(node_buf, 0, srv_cert_der, want) <= 0) return -1;
    srv_cert_der_len = (uint32_t)want;

    if (!vfs_find("cluster/tls-key.bin", 0, node_buf)) {
        serial_puts("[TLS1.3-S] no cluster/tls-key.bin on osfs2\n");
        return -1;
    }
    n = (node_t *)node_buf;
    if (n->size < 32) return -1;
    if (vfs_read(node_buf, 0, srv_priv_be, 32) <= 0) return -1;

    srv_identity_loaded = true;
    serial_puts("[TLS1.3-S] identity loaded (cert=");
    serial_putdec((uint64_t)srv_cert_der_len);
    serial_puts(" B, key=32 B)\n");
    return 0;
}

/* ── Public: handshake on an already-accepted TCP conn ──────── */

int tls13_server_handshake(int tcp_conn)
{
    if (!srv_identity_loaded) {
        serial_puts("[TLS1.3-S] handshake skipped: no identity loaded\n");
        return -1;
    }

    s_memset(&srv13, 0, sizeof srv13);
    srv13.tcp_conn = tcp_conn;

    /* 1. Read ClientHello (one record). */
    static uint8_t ch_body[8192];
    uint8_t ct; uint32_t ch_len;
    if (read_record(tcp_conn, &ct, ch_body, sizeof ch_body, &ch_len) < 0) {
        serial_puts("[TLS1.3-S] no CH record\n"); return -1;
    }
    if (ct != TLS_CONTENT_HANDSHAKE) { return -1; }
    if (parse_client_hello(ch_body, ch_len) < 0) return -1;
    th_append(ch_body, ch_len);
    serial_puts("[TLS1.3-S] ClientHello parsed\n");

    /* 2. Generate server ephemeral keypair + random. */
    random_get_bytes(srv13.server_priv, 32);
    srv13.server_priv[0]  &= 248;
    srv13.server_priv[31] &= 127;
    srv13.server_priv[31] |= 64;
    x25519_public(srv13.server_pub, srv13.server_priv);
    random_get_bytes(srv13.server_random, 32);

    /* 3. Build + send ServerHello. */
    static uint8_t sh[256];
    int sh_len = build_server_hello(sh, sizeof sh);
    if (sh_len < 0) return -1;
    if (send_plain_handshake(tcp_conn, sh, (uint32_t)sh_len) < 0) return -1;
    th_append(sh, (uint32_t)sh_len);
    serial_puts("[TLS1.3-S] ServerHello sent\n");

    /* 4. Compute ECDH shared + derive handshake secrets. */
    x25519(srv13.shared, srv13.server_priv, srv13.client_pub);

    uint8_t early_secret[32];
    hkdf_extract(zero32, 32, zero32, 32, early_secret);
    uint8_t empty_hash[32];
    sha256((const uint8_t *)"", 0, empty_hash);
    uint8_t derived1[32];
    hkdf_expand_label(early_secret, "derived", empty_hash, 32, derived1, 32);
    hkdf_extract(derived1, 32, srv13.shared, 32, srv13.handshake_secret);

    uint8_t th[32]; th_compute(th);
    hkdf_expand_label(srv13.handshake_secret, "c hs traffic", th, 32, srv13.c_hs_traffic, 32);
    hkdf_expand_label(srv13.handshake_secret, "s hs traffic", th, 32, srv13.s_hs_traffic, 32);
    derive_key_iv(srv13.c_hs_traffic, srv13.c_hs_key, srv13.c_hs_iv);
    derive_key_iv(srv13.s_hs_traffic, srv13.s_hs_key, srv13.s_hs_iv);

    /* Optional: send ChangeCipherSpec for middlebox compatibility. */
    {
        uint8_t ccs[6] = { TLS_CONTENT_CHANGE_CIPHER, 0x03, 0x03,
                           0x00, 0x01, 0x01 };
        (void)net_tcp_send(tcp_conn, ccs, 6);
    }

    /* 5. Send {EE, Certificate, CertVerify, Finished} as encrypted handshake. */
    static uint8_t flight[8192];
    uint32_t fl = 0;
    int n;
    int ee_off = (int)fl;
    n = build_encrypted_extensions(flight + fl);
    if (n < 0) return -1;
    fl += (uint32_t)n;
    th_append(flight + ee_off, (uint32_t)n);

    int cert_off = (int)fl;
    n = build_certificate(flight + fl, sizeof flight - fl);
    if (n < 0) return -1;
    fl += (uint32_t)n;
    th_append(flight + cert_off, (uint32_t)n);

    int cv_off = (int)fl;
    n = build_certificate_verify(flight + fl, sizeof flight - fl);
    if (n < 0) return -1;
    fl += (uint32_t)n;
    th_append(flight + cv_off, (uint32_t)n);

    int fin_off = (int)fl;
    n = build_server_finished(flight + fl);
    if (n < 0) return -1;
    fl += (uint32_t)n;
    th_append(flight + fin_off, (uint32_t)n);

    /* AEAD-wrap the whole flight as one APP_DATA record. */
    if (send_encrypted(tcp_conn, TLS_CONTENT_HANDSHAKE,
                        flight, fl, srv13.s_hs_key, srv13.s_hs_iv,
                        srv13.s_seq++) < 0) {
        serial_puts("[TLS1.3-S] send_encrypted flight failed\n");
        return -1;
    }
    serial_puts("[TLS1.3-S] server flight {EE,Cert,CV,Fin} sent\n");

    /* 6. Read client Finished (under c_hs_traffic). */
    static uint8_t cfb[1024];
    uint32_t cfl;
    /* Tolerate one ChangeCipherSpec from middleboxes. */
    for (int i = 0; i < 2; i++) {
        if (read_record(tcp_conn, &ct, cfb, sizeof cfb, &cfl) < 0) {
            serial_puts("[TLS1.3-S] client Finished read failed\n");
            return -1;
        }
        if (ct == TLS_CONTENT_CHANGE_CIPHER) continue;
        if (ct != TLS_CONTENT_APP_DATA) return -1;
        break;
    }
    uint8_t inner; uint32_t pt_len;
    if (decrypt_record(cfb, cfl, srv13.c_hs_key, srv13.c_hs_iv,
                        srv13.c_seq++, &inner, &pt_len) < 0) {
        serial_puts("[TLS1.3-S] client Finished decrypt FAILED\n");
        return -1;
    }
    if (inner != TLS_CONTENT_HANDSHAKE || pt_len < 4) return -1;
    if (cfb[0] != HS_FINISHED) return -1;
    uint32_t mlen = ((uint32_t)cfb[1] << 16) | ((uint32_t)cfb[2] << 8) | cfb[3];
    if (mlen != 32 || 4 + mlen > pt_len) return -1;

    /* Verify client Finished against transcript BEFORE we append it. */
    uint8_t th_pre[32]; th_compute(th_pre);
    uint8_t cfk[32];
    hkdf_expand_label(srv13.c_hs_traffic, "finished", 0, 0, cfk, 32);
    uint8_t want[32];
    hmac_sha256(cfk, 32, th_pre, 32, want);
    if (!s_memeq_ct(want, cfb + 4, 32)) {
        serial_puts("[TLS1.3-S] client Finished MAC FAIL\n");
        return -1;
    }
    serial_puts("[TLS1.3-S] client Finished verified OK\n");
    th_append(cfb, 4 + mlen);

    /* 7. Derive app-traffic secrets. */
    uint8_t derived2[32];
    hkdf_expand_label(srv13.handshake_secret, "derived", empty_hash, 32, derived2, 32);
    uint8_t master[32];
    hkdf_extract(derived2, 32, zero32, 32, master);
    uint8_t th_final[32]; th_compute(th_final);
    hkdf_expand_label(master, "c ap traffic", th_final, 32, srv13.c_ap_traffic, 32);
    hkdf_expand_label(master, "s ap traffic", th_final, 32, srv13.s_ap_traffic, 32);
    derive_key_iv(srv13.c_ap_traffic, srv13.c_ap_key, srv13.c_ap_iv);
    derive_key_iv(srv13.s_ap_traffic, srv13.s_ap_key, srv13.s_ap_iv);
    srv13.c_seq = 0; srv13.s_seq = 0;
    srv13.active = true;
    serial_puts("[TLS1.3-S] handshake complete — app keys live\n");
    return 0;
}

/* ── Self-test (no network): handshake against a canned ClientHello
 * is not feasible without a paired client run.  Instead we sanity-
 * check identity loading and the key schedule with a known PSK so
 * the boot path can fail loudly if the cert/key isn't on osfs2. */
int tls13_server_self_test(void)
{
    if (!srv_identity_loaded) return -1;
    if (srv_cert_der_len < 100) {
        serial_puts("[TLS1.3-S] cert suspiciously short\n");
        return -1;
    }
    serial_puts("[TLS1.3-S] self-test: identity present\n");
    return 0;
}

/* ── Public: spawn a TCP listener kthread that handshakes inbound ── */

static volatile int srv_listener_running = 0;
static uint16_t     srv_listen_port = 0;

static void srv_listener_thread(void *unused)
{
    (void)unused;
    int lst = net_tcp_listen(srv_listen_port);
    if (lst < 0) {
        serial_puts("[TLS1.3-S] listen failed\n");
        srv_listener_running = 0;
        return;
    }
    serial_puts("[TLS1.3-S] listener up on port ");
    serial_putdec((uint64_t)srv_listen_port); serial_puts("\n");
    while (srv_listener_running) {
        int conn = net_tcp_accept(lst, 10);   /* 100 ms poll */
        if (conn < 0) { sched_yield(); continue; }
        serial_puts("[TLS1.3-S] inbound conn\n");
        int rc = tls13_server_handshake(conn);
        if (rc == 0) {
            /* Drain one app-data record from client (smoke) before tear-down. */
            serial_puts("[TLS1.3-S] handshake OK — closing\n");
        } else {
            serial_puts("[TLS1.3-S] handshake FAILED\n");
        }
        net_tcp_close(conn);
    }
    serial_puts("[TLS1.3-S] listener stopped\n");
}

int tls13_server_listen(uint16_t port)
{
    if (!srv_identity_loaded) return -1;
    if (srv_listener_running) return 0;
    srv_listen_port = port;
    srv_listener_running = 1;
    int kt = kthread_create("tls13-server", srv_listener_thread, 0);
    if (kt < 0) { srv_listener_running = 0; return -1; }
    return 0;
}
