#!/usr/bin/env python3
"""
OsitoK — Extract SASS code from cubin ELF and generate C byte array.

Usage: python3 cubin2array.py <cubin_file> <kernel_name>

Cubin is an ELF file. The .text.<kernel_name> section contains the SASS binary.
If no named section found, uses the first .text section.

Output: C header with static const uint8_t array + metadata.
"""

import sys
import struct
import os

def read_elf_sections(data):
    """Parse ELF64 section headers."""
    if data[:4] != b'\x7fELF':
        raise ValueError("Not an ELF file")

    ei_class = data[4]
    if ei_class != 2:
        raise ValueError(f"Expected ELF64, got class {ei_class}")

    # ELF64 header
    e_shoff = struct.unpack_from('<Q', data, 40)[0]
    e_shentsize = struct.unpack_from('<H', data, 58)[0]
    e_shnum = struct.unpack_from('<H', data, 60)[0]
    e_shstrndx = struct.unpack_from('<H', data, 62)[0]

    sections = []
    for i in range(e_shnum):
        off = e_shoff + i * e_shentsize
        sh_name = struct.unpack_from('<I', data, off)[0]
        sh_type = struct.unpack_from('<I', data, off + 4)[0]
        sh_flags = struct.unpack_from('<Q', data, off + 8)[0]
        sh_addr = struct.unpack_from('<Q', data, off + 16)[0]
        sh_offset = struct.unpack_from('<Q', data, off + 24)[0]
        sh_size = struct.unpack_from('<Q', data, off + 32)[0]
        sections.append({
            'name_idx': sh_name,
            'type': sh_type,
            'flags': sh_flags,
            'addr': sh_addr,
            'offset': sh_offset,
            'size': sh_size,
        })

    # Resolve section names from string table
    if e_shstrndx < len(sections):
        strtab = sections[e_shstrndx]
        strtab_data = data[strtab['offset']:strtab['offset'] + strtab['size']]
        for s in sections:
            end = strtab_data.find(b'\x00', s['name_idx'])
            s['name'] = strtab_data[s['name_idx']:end].decode('ascii', errors='replace')
    else:
        for s in sections:
            s['name'] = ''

    return sections


def find_text_section(sections, kernel_name):
    """Find the .text section for the given kernel."""
    # Try exact match: .text.<kernel_name>
    for s in sections:
        if s['name'] == f'.text.{kernel_name}':
            return s

    # Try any .text section with EXECINSTR flag (SHF_EXECINSTR = 0x4)
    for s in sections:
        if s['name'].startswith('.text') and (s['flags'] & 0x4):
            return s

    # Fallback: first PROGBITS section with EXECINSTR
    for s in sections:
        if s['type'] == 1 and (s['flags'] & 0x4):  # SHT_PROGBITS + EXECINSTR
            return s

    return None


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <cubin_file> <kernel_name>", file=sys.stderr)
        sys.exit(1)

    cubin_path = sys.argv[1]
    kernel_name = sys.argv[2]

    with open(cubin_path, 'rb') as f:
        data = f.read()

    sections = read_elf_sections(data)
    text = find_text_section(sections, kernel_name)

    if text is None:
        print(f"ERROR: No .text section found for kernel '{kernel_name}'", file=sys.stderr)
        print("Available sections:", file=sys.stderr)
        for s in sections:
            print(f"  {s['name']} (type={s['type']}, flags=0x{s['flags']:x}, size={s['size']})", file=sys.stderr)
        sys.exit(1)

    code = data[text['offset']:text['offset'] + text['size']]
    num_insns = len(code) // 16  # 128-bit instructions

    # Generate C header
    guard = f"OSITOK_KERN_{kernel_name.upper()}_H"
    print(f"/* Auto-generated by cubin2array.py from {os.path.basename(cubin_path)} */")
    print(f"/* Kernel: {kernel_name}, {len(code)} bytes, {num_insns} instructions */")
    print(f"/* Section: {text['name']} */")
    print(f"")
    print(f"#ifndef {guard}")
    print(f"#define {guard}")
    print(f"")
    print(f"static const uint8_t __attribute__((aligned(256)))")
    print(f"sass_code_{kernel_name}[] = {{")

    for i in range(0, len(code), 16):
        chunk = code[i:i+16]
        hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
        comment = f"/* insn {i//16}: "
        if len(chunk) >= 8:
            opcode = struct.unpack_from('<Q', chunk, 0)[0]
            comment += f"0x{opcode:016x}"
        comment += " */"
        print(f"    {hex_bytes},  {comment}")

    print(f"}};")
    print(f"")
    print(f"#define SASS_{kernel_name.upper()}_SIZE     {len(code)}")
    print(f"#define SASS_{kernel_name.upper()}_INSNS    {num_insns}")
    print(f"")
    print(f"#endif /* {guard} */")


if __name__ == '__main__':
    main()
