/* OsitoK W4.3: minimal stub of mesa's generated vk_struct_type_cast.h.
 *
 * Real Mesa file is generated by vk_struct_type_cast_gen.py and provides
 * vk_find_struct(p, sType) — walking pNext chains to find a typed struct.
 * For our compile-only needs in zink we provide a no-op implementation
 * that returns NULL; callers handle NULL gracefully (the chain just
 * doesn't carry that ext struct in our setup). */
#ifndef OSITOK_VK_STRUCT_TYPE_CAST_H
#define OSITOK_VK_STRUCT_TYPE_CAST_H 1

#include <vulkan/vulkan_core.h>

#define VK_STRUCT_TYPE_CAST(__expr, __struct_type, __vk_type) \
    ((__struct_type *)(__expr))

#define vk_find_struct(__start, __sType_str) \
    vk_find_struct_impl((VkBaseOutStructure *)(__start), \
                        VK_STRUCTURE_TYPE_ ## __sType_str)

#define vk_find_struct_const(__start, __sType_str) \
    ((const void *)vk_find_struct_impl((VkBaseOutStructure *)(__start), \
                                       VK_STRUCTURE_TYPE_ ## __sType_str))

static inline void *
vk_find_struct_impl(VkBaseOutStructure *start, VkStructureType sType)
{
    while (start) {
        if (start->sType == sType)
            return start;
        start = start->pNext;
    }
    return (void *)0;
}

#endif /* OSITOK_VK_STRUCT_TYPE_CAST_H */
