/*
 * OsitoK x86-64 — SASS Kernel Infrastructure (X37)
 *
 * Pre-encoded SASS compute kernels for bare-metal GPU dispatch.
 * Kernels are raw SASS instruction bytes uploaded to VRAM via PRAMIN.
 *
 * X37 kernels:
 *   - nop:       Single EXIT instruction (16B). Dispatch smoke test.
 *   - s2r_exit:  S2R R2,SR_TID.X + EXIT (32B). Register read test.
 *   - nop4_exit: 4×NOP + EXIT (80B). Multi-instruction fetch test.
 *
 * Kernel binaries uploaded to VRAM at SASS_VRAM_OFFSET_MB (256MB).
 * Each kernel is 256-byte aligned in VRAM for QMD compatibility.
 *
 * Reference: NVIDIA open-gpu-doc (QMD), DocumentSASS (SASS ISA),
 *            turingas (SM75 assembler), CuAssembler.
 */

#include "../include/types.h"
#include "gpu.h"
#include "sass.h"

/* ── Compiled SASS kernels from PTX (X41) ──────────────────── */
/* Generated by: scripts/compile_kernels.sh (ptxas sm_75)      */
#include "../kernels/generated/gemv_q4_0_code.h"
#include "../kernels/generated/rmsnorm_code.h"
#include "../kernels/generated/softmax_code.h"
#include "../kernels/generated/rope_code.h"
#include "../kernels/generated/vec_add_code.h"
#include "../kernels/generated/vec_mul_code.h"
#include "../kernels/generated/silu_mul_code.h"
#include "../kernels/generated/add_inplace_code.h"

/* ── External Functions ──────────────────────────────────── */

extern void serial_puts(const char *s);
extern void serial_puthex(uint64_t val, int digits);
extern void serial_putdec(uint64_t val);
extern void fb_puts(const char *s);
extern void fb_puts_color(const char *s, uint32_t color);
extern void fb_putdec(uint64_t val);

extern void *mem_alloc_aligned(uint64_t size, uint64_t alignment);

/* rdtsc for timing */
static inline uint64_t rdtsc_sass(void)
{
    uint64_t cnt;
    __asm__ volatile ("mrs %0, CNTPCT_EL0" : "=r"(cnt));
    return cnt;
}

/* ── SASS State ──────────────────────────────────────────── */

static sass_state_t sass_state;

/* ══════════════════════════════════════════════════════════
 *  Pre-encoded SASS Kernel Binaries (SM75 / Turing)
 *
 *  Each instruction is 128 bits (16 bytes), stored little-endian:
 *    bytes  0-7:  opcode word (operation + registers)
 *    bytes 8-15:  control word (scheduling + dependencies)
 *
 *  Encoding verified via nvdisasm / DocumentSASS / turingas.
 * ══════════════════════════════════════════════════════════ */

/* ── Kernel: nop ──────────────────────────────────────────
 *
 * Single EXIT instruction. Minimal dispatch smoke test.
 * When dispatched via QMD with RELEASE0 semaphore, the hardware
 * writes sem_payload on kernel completion — proving:
 *   QMD dispatch → GPU execution → semaphore release.
 *
 * SASS:
 *   EXIT;    // 0x000000000000794d | 0x000fea0003800000
 *
 * Requirements: 2 registers (minimum), 0 shared mem, 0 barriers.
 */
static const uint8_t __attribute__((aligned(256))) sass_code_nop[] = {
    /* EXIT */
    0x4d, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  /* opcode */
    0x00, 0x00, 0x80, 0x03, 0x00, 0xea, 0x0f, 0x00,  /* control */
};

/* ── Kernel: s2r_exit ─────────────────────────────────────
 *
 * Read thread ID into R2, then exit.
 * Tests special register access — proves instruction execution
 * beyond immediate EXIT.
 *
 * SASS:
 *   S2R R2, SR_TID.X;  // 0x0000000000027919 | 0x000e220000002100
 *   EXIT;               // 0x000000000000794d | 0x000fea0003800000
 *
 * Requirements: 4 registers, 0 shared mem, 0 barriers.
 */
static const uint8_t __attribute__((aligned(256))) sass_code_s2r_exit[] = {
    /* S2R R2, SR_TID.X */
    0x19, 0x79, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00,  /* opcode */
    0x00, 0x21, 0x00, 0x00, 0x00, 0x22, 0x0e, 0x00,  /* control */
    /* EXIT */
    0x4d, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  /* opcode */
    0x00, 0x00, 0x80, 0x03, 0x00, 0xea, 0x0f, 0x00,  /* control */
};

/* ── Kernel: nop4_exit ────────────────────────────────────
 *
 * 4×NOP + EXIT. Tests multi-instruction kernel execution.
 * Useful for verifying instruction fetch works beyond first
 * cache line (16 bytes).
 *
 * SASS:
 *   NOP; NOP; NOP; NOP;
 *   EXIT;
 *
 * Requirements: 2 registers, 0 shared mem, 0 barriers.
 */
static const uint8_t __attribute__((aligned(256))) sass_code_nop4_exit[] = {
    /* NOP ×4 */
    0x18, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0xc0, 0x0f, 0x00,
    0x18, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0xc0, 0x0f, 0x00,
    0x18, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0xc0, 0x0f, 0x00,
    0x18, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0xc0, 0x0f, 0x00,
    /* EXIT */
    0x4d, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x80, 0x03, 0x00, 0xea, 0x0f, 0x00,
};

/* ── Kernel: store_pattern ────────────────────────────────
 *
 * Writes 0xCAFEBABE to VRAM+256MB+1MB (GPU VA 0x10100000).
 * Proves: compute dispatch → GMMU translation → STG to VRAM.
 * Must be dispatched as 1 thread, 1 block.
 *
 * SASS:
 *   MOV R2, 0x10100000;     // target address low (identity-mapped VRAM)
 *   MOV R3, 0x00000000;     // target address high (< 4GB = 0)
 *   MOV R0, 0xCAFEBABE;     // test pattern
 *   STG.E [R2], R0;         // store to VRAM (64-bit addr = R2:R3)
 *   EXIT;
 *
 * Requirements: 4 registers, 0 shared mem, 0 barriers.
 */
static const uint8_t __attribute__((aligned(256))) sass_code_store_pattern[] = {
    /* MOV R2, 0x10100000 — target VRAM address (low 32 bits) */
    0x02, 0x78, 0x02, 0x00, 0x00, 0x00, 0x10, 0x10,  /* opcode */
    0x00, 0x0f, 0x00, 0x00, 0x00, 0xca, 0x0f, 0x00,  /* control */
    /* MOV R3, 0x00000000 — address high = 0 */
    0x02, 0x78, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x0f, 0x00, 0x00, 0x00, 0xca, 0x0f, 0x00,
    /* MOV R0, 0xCAFEBABE — test pattern */
    0x02, 0x78, 0x00, 0x00, 0xBE, 0xBA, 0xFE, 0xCA,
    0x00, 0x0f, 0x00, 0x00, 0x00, 0xca, 0x0f, 0x00,
    /* STG.E [R2], R0 — store R0 to address R2:R3 */
    0x86, 0x73, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00,
    0x00, 0xe9, 0x10, 0x00, 0x00, 0xe2, 0x0f, 0x00,
    /* EXIT */
    0x4d, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x80, 0x03, 0x00, 0xea, 0x0f, 0x00,
};

/* ── Kernel: vec_add_f32 ─────────────────────────────────
 *
 * dst[i] = a[i] + b[i], 1 block of 256 threads.
 * Base addresses embedded as MOV immediates (patched before upload).
 * Uses IADD3 for ×4 byte offset: R1 = R0+R0, R1 = R1+R1.
 *
 * SASS:
 *   S2R R0, SR_TID.X;            // threadIdx.x
 *   IADD3 R1, R0, R0, RZ;        // R1 = 2*tid
 *   IADD3 R1, R1, R1, RZ;        // R1 = 4*tid (byte offset)
 *   MOV R3, 0x00000000;           // addr high = 0
 *   MOV R2, <src_a>;              // src_a base [PATCH offset 0x44]
 *   IADD3 R4, R2, R1, RZ;        // R4 = src_a + byte_offset
 *   LDG.E R10, [R4];             // R10 = a[tid]
 *   MOV R2, <src_b>;              // src_b base [PATCH offset 0x74]
 *   IADD3 R4, R2, R1, RZ;        // R4 = src_b + byte_offset
 *   NOP; NOP; NOP; NOP;           // wait for R10 (LDG latency)
 *   LDG.E R11, [R4];             // R11 = b[tid]
 *   NOP; NOP; NOP; NOP;           // wait for R11 (LDG latency)
 *   FADD R12, R10, R11;           // R12 = a[i] + b[i]
 *   MOV R2, <dst>;                // dst base [PATCH offset 0x124]
 *   IADD3 R4, R2, R1, RZ;        // R4 = dst + byte_offset
 *   STG.E [R4], R12;             // store result
 *   EXIT;
 *
 * Patch offsets (byte positions of MOV immediate fields):
 *   src_a: byte 0x44 (instruction 4, bytes 4-7 of word0)
 *   src_b: byte 0x74 (instruction 7, bytes 4-7 of word0)
 *   dst:   byte 0x124 (instruction 18, bytes 4-7 of word0)
 *
 * Requirements: 16 registers, 0 shared mem, 0 barriers, max 256 threads.
 */
static uint8_t __attribute__((aligned(256))) sass_code_vec_add_f32[] = {
    /* [0] S2R R0, SR_TID.X */
    0x19, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x21, 0x00, 0x00, 0x00, 0x22, 0x0e, 0x00,
    /* [1] IADD3 R1, R0, R0, RZ — R1 = 2*tid */
    0x10, 0x72, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
    0xff, 0xe0, 0xff, 0x07, 0x00, 0xc0, 0x0f, 0x00,
    /* [2] IADD3 R1, R1, R1, RZ — R1 = 4*tid */
    0x10, 0x72, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00,
    0xff, 0xe0, 0xff, 0x07, 0x00, 0xc0, 0x0f, 0x00,
    /* [3] MOV R3, 0x00000000 — address high */
    0x02, 0x78, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x0f, 0x00, 0x00, 0x00, 0xca, 0x0f, 0x00,
    /* [4] MOV R2, <src_a> — PATCH bytes 0x44-0x47 */
    0x02, 0x78, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x0f, 0x00, 0x00, 0x00, 0xca, 0x0f, 0x00,
    /* [5] IADD3 R4, R2, R1, RZ — R4 = src_a + offset */
    0x10, 0x72, 0x04, 0x02, 0x01, 0x00, 0x00, 0x00,
    0xff, 0xe0, 0xff, 0x07, 0x00, 0xc0, 0x0f, 0x00,
    /* [6] NOP — stall for IADD3 */
    0x18, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0xc0, 0x0f, 0x00,
    /* [7] LDG.E R10, [R4] — load a[tid] via R4:R5 */
    0x81, 0x73, 0x0a, 0x04, 0x00, 0x00, 0x00, 0x00,
    0x00, 0xe9, 0x1e, 0x00, 0x00, 0xa2, 0x0e, 0x00,
    /* [8] MOV R2, <src_b> — PATCH bytes 0x84-0x87 */
    0x02, 0x78, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x0f, 0x00, 0x00, 0x00, 0xca, 0x0f, 0x00,
    /* [9] IADD3 R4, R2, R1, RZ — R4 = src_b + offset */
    0x10, 0x72, 0x04, 0x02, 0x01, 0x00, 0x00, 0x00,
    0xff, 0xe0, 0xff, 0x07, 0x00, 0xc0, 0x0f, 0x00,
    /* [10] NOP — stall for IADD3 */
    0x18, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0xc0, 0x0f, 0x00,
    /* [11] LDG.E R11, [R4] — load b[tid] via R4:R5 */
    0x81, 0x73, 0x0b, 0x04, 0x00, 0x00, 0x00, 0x00,
    0x00, 0xe9, 0x1e, 0x00, 0x00, 0xa2, 0x0e, 0x00,
    /* [12-15] NOP x4 — wait for LDG latency */
    0x18, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0xc0, 0x0f, 0x00,
    0x18, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0xc0, 0x0f, 0x00,
    0x18, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0xc0, 0x0f, 0x00,
    0x18, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0xc0, 0x0f, 0x00,
    /* [16] FADD R12, R10, R11 — result = a[i] + b[i] */
    0x21, 0x72, 0x0c, 0x0a, 0x0b, 0x00, 0x00, 0x00,
    0xff, 0x00, 0x00, 0x00, 0x00, 0xc0, 0x0f, 0x00,
    /* [17] NOP — stall for FADD */
    0x18, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0xc0, 0x0f, 0x00,
    /* [18] MOV R2, <dst> — PATCH bytes 0x124-0x127 */
    0x02, 0x78, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x0f, 0x00, 0x00, 0x00, 0xca, 0x0f, 0x00,
    /* [19] IADD3 R4, R2, R1, RZ — R4 = dst + offset */
    0x10, 0x72, 0x04, 0x02, 0x01, 0x00, 0x00, 0x00,
    0xff, 0xe0, 0xff, 0x07, 0x00, 0xc0, 0x0f, 0x00,
    /* [20] NOP — stall for IADD3 */
    0x18, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0xc0, 0x0f, 0x00,
    /* [21] STG.E [R4], R12 — store result */
    0x86, 0x73, 0x00, 0x04, 0x0c, 0x00, 0x00, 0x00,
    0x00, 0xe9, 0x10, 0x00, 0x00, 0xe2, 0x0f, 0x00,
    /* [22] EXIT */
    0x4d, 0x79, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x80, 0x03, 0x00, 0xea, 0x0f, 0x00,
};

/* Patch offsets for vec_add_f32 kernel (MOV immediate fields) */
#define VEC_ADD_PATCH_SRC_A   0x44   /* instruction [4], bytes 4-7 */
#define VEC_ADD_PATCH_SRC_B   0x84   /* instruction [8], bytes 4-7 */
#define VEC_ADD_PATCH_DST     0x124  /* instruction [18], bytes 4-7 */

/* ── Kernel Registration ─────────────────────────────────── */

static void sass_register_kernel(const char *name, const uint8_t *code,
                                  uint32_t code_size, uint32_t regs,
                                  uint32_t smem, uint32_t barriers,
                                  uint32_t max_threads)
{
    if (sass_state.count >= SASS_MAX_KERNELS) return;

    sass_kernel_t *k = &sass_state.kernels[sass_state.count];

    /* Copy name */
    uint32_t i;
    for (i = 0; i < SASS_KERNEL_NAME_MAX - 1 && name[i]; i++)
        k->name[i] = name[i];
    k->name[i] = '\0';

    k->code           = code;
    k->code_size      = code_size;
    k->num_insns      = code_size / SASS_INSN_SIZE;
    k->register_count = regs;
    k->shared_mem     = smem;
    k->barrier_count  = barriers;
    k->max_threads    = max_threads;
    k->vram_addr      = 0;
    k->uploaded       = false;

    sass_state.count++;
}

/* ── VRAM Upload via PRAMIN ──────────────────────────────── */

int sass_upload_kernel(sass_kernel_t *k)
{
    if (!k || !k->code || k->code_size == 0) return -1;

    gpu_probe_t *p = gpu_get_probe();
    if (!p || !p->present || p->vram_size_mb == 0) {
        serial_puts("[SASS] No GPU/VRAM for kernel upload\n");
        return -1;
    }

    /* Check VRAM bounds */
    uint32_t aligned_size = (k->code_size + 255) & ~255u;
    uint64_t vram_bytes = (uint64_t)p->vram_size_mb * 1024 * 1024;
    if (sass_state.vram_next + aligned_size > vram_bytes) {
        serial_puts("[SASS] VRAM overflow for kernel '");
        serial_puts(k->name);
        serial_puts("'\n");
        return -1;
    }

    /* Assign VRAM address (256-byte aligned) */
    k->vram_addr = sass_state.vram_next;
    sass_state.vram_next += aligned_size;

    serial_puts("[SASS] Uploading '");
    serial_puts(k->name);
    serial_puts("' (");
    serial_putdec(k->code_size);
    serial_puts("B, ");
    serial_putdec(k->num_insns);
    serial_puts(" insns) -> VRAM+0x");
    serial_puthex(k->vram_addr, 8);
    serial_puts("\n");

    /* Upload via PRAMIN window (1MB window, same pattern as X18/X19) */
    uint32_t saved_window = gpu_reg_read(NV_PBUS_BAR0_WINDOW);

    /* Set PRAMIN window to kernel VRAM offset */
    uint32_t window_val = (uint32_t)(k->vram_addr >> 16);
    gpu_reg_write(NV_PBUS_BAR0_WINDOW, window_val);
    wmb();

    /* Write kernel code through PRAMIN */
    uint32_t dwords = k->code_size / 4;
    const uint32_t *src = (const uint32_t *)k->code;
    uint32_t pramin_offset = (uint32_t)(k->vram_addr & 0xFFFF);

    for (uint32_t i = 0; i < dwords; i++)
        gpu_reg_write(NV_PRAMIN_BASE + pramin_offset + i * 4, src[i]);
    wmb();

    /* Verify first 2 dwords */
    rmb();
    uint32_t v0 = gpu_reg_read(NV_PRAMIN_BASE + pramin_offset);
    uint32_t v1 = gpu_reg_read(NV_PRAMIN_BASE + pramin_offset + 4);

    bool verify_ok = (v0 == src[0] && v1 == src[1]);

    /* Restore PRAMIN window */
    gpu_reg_write(NV_PBUS_BAR0_WINDOW, saved_window);
    wmb();

    if (verify_ok) {
        serial_puts("[SASS] Upload verified (0x");
        serial_puthex(v0, 8);
        serial_puts(" 0x");
        serial_puthex(v1, 8);
        serial_puts(")\n");
        k->uploaded = true;
    } else {
        serial_puts("[SASS] Upload verify FAILED (expected 0x");
        serial_puthex(src[0], 8);
        serial_puts("/0x");
        serial_puthex(src[1], 8);
        serial_puts(", got 0x");
        serial_puthex(v0, 8);
        serial_puts("/0x");
        serial_puthex(v1, 8);
        serial_puts(")\n");
    }

    return verify_ok ? 0 : -1;
}

/* ── Smoke Test: dispatch NOP kernel ─────────────────────── */

int sass_smoke_test(void)
{
    serial_puts("[SASS] -- Smoke test: dispatch NOP kernel --\n");

    sass_kernel_t *nop = sass_get_kernel("nop");
    if (!nop || !nop->uploaded) {
        serial_puts("[SASS] NOP kernel not available\n");
        return -1;
    }

    /* Allocate semaphore (page-aligned for GPU access) */
    uint32_t *sem = (uint32_t *)mem_alloc_aligned(4096, 4096);
    if (!sem) {
        serial_puts("[SASS] Failed to allocate semaphore\n");
        return -1;
    }
    *sem = 0;
    wmb();

    uint64_t sem_phys = (uint64_t)(uintptr_t)sem;

    /* Build dispatch descriptor */
    compute_dispatch_t desc;
    memset(&desc, 0, sizeof(desc));
    desc.program_addr   = nop->vram_addr;  /* VRAM address of kernel */
    desc.grid_x         = 1;
    desc.grid_y         = 1;
    desc.grid_z         = 1;
    desc.block_x        = 1;   /* Single thread */
    desc.block_y        = 1;
    desc.block_z        = 1;
    desc.register_count = nop->register_count;
    desc.shared_mem_size = 0;
    desc.barrier_count  = 0;
    desc.sem_addr       = sem_phys;
    desc.sem_payload    = 0xD15BA7C4;  /* "DISPATCH" marker */

    serial_puts("[SASS] Dispatching NOP: prog=0x");
    serial_puthex(nop->vram_addr, 16);
    serial_puts(" sem=0x");
    serial_puthex(sem_phys, 16);
    serial_puts("\n");

    /* Dispatch */
    int ret = gsp_compute_dispatch(&desc);
    if (ret < 0) {
        serial_puts("[SASS] Dispatch failed (expected without full boot chain)\n");
        return -1;
    }

    /* Wait for completion (short timeout — don't expect success without GSP-RM) */
    ret = gsp_compute_wait(sem_phys, 0xD15BA7C4, 500);
    if (ret == 0) {
        serial_puts("[SASS] *** NOP kernel completed! GPU compute works! ***\n");
        fb_puts_color(" SASS: NOP kernel OK!\n", 0x0000FF00);
        return 0;
    }

    serial_puts("[SASS] NOP kernel timeout (expected without full GSP boot chain)\n");
    serial_puts("[SASS] Infrastructure verified, awaiting hardware validation\n");
    return -1;
}

/* ── Public API ──────────────────────────────────────────── */

sass_kernel_t *sass_get_kernel(const char *name)
{
    if (!name) return NULL;
    for (uint32_t i = 0; i < sass_state.count; i++) {
        /* Simple strcmp */
        const char *a = sass_state.kernels[i].name;
        const char *b = name;
        while (*a && *b && *a == *b) { a++; b++; }
        if (*a == '\0' && *b == '\0')
            return &sass_state.kernels[i];
    }
    return NULL;
}

sass_state_t *sass_get_state(void)
{
    return &sass_state;
}

int sass_init(void)
{
    serial_puts("\n[SASS] == X37: SASS Kernel Infrastructure ==\n");

    gpu_probe_t *p = gpu_get_probe();
    if (!p || !p->present) {
        serial_puts("[SASS] No GPU detected, skipping\n");
        return -1;
    }

    memset(&sass_state, 0, sizeof(sass_state));

    /* Calculate VRAM base address for kernels */
    sass_state.vram_base = (uint64_t)SASS_VRAM_OFFSET_MB * 1024 * 1024;
    sass_state.vram_next = sass_state.vram_base;

    serial_puts("[SASS] Kernel VRAM base: 0x");
    serial_puthex(sass_state.vram_base, 8);
    serial_puts(" (");
    serial_putdec(SASS_VRAM_OFFSET_MB);
    serial_puts("MB)\n");

    /* ── Register pre-encoded kernels ── */

    sass_register_kernel("nop", sass_code_nop,
                         sizeof(sass_code_nop), 2, 0, 0, 1024);

    sass_register_kernel("s2r_exit", sass_code_s2r_exit,
                         sizeof(sass_code_s2r_exit), 4, 0, 0, 1024);

    sass_register_kernel("nop4_exit", sass_code_nop4_exit,
                         sizeof(sass_code_nop4_exit), 2, 0, 0, 1024);

    sass_register_kernel("store_pattern", sass_code_store_pattern,
                         sizeof(sass_code_store_pattern), 4, 0, 0, 1);

    sass_register_kernel("vec_add_f32", sass_code_vec_add_f32,
                         sizeof(sass_code_vec_add_f32), 16, 0, 0, 256);

    /* ── X41: Compiled PTX kernels (ptxas sm_75 → SASS) ── */

    sass_register_kernel("gemv_q4_0", sass_code_gemv_q4_0,
                         SASS_GEMV_Q4_0_SIZE, 24, 32768, 1, 256);

    sass_register_kernel("rmsnorm", sass_code_rmsnorm,
                         SASS_RMSNORM_SIZE, 16, 132, 1, 256);

    sass_register_kernel("softmax", sass_code_softmax,
                         SASS_SOFTMAX_SIZE, 16, 136, 1, 256);

    sass_register_kernel("rope", sass_code_rope,
                         SASS_ROPE_SIZE, 24, 0, 0, 256);

    sass_register_kernel("vec_add_ptx", sass_code_vec_add,
                         SASS_VEC_ADD_SIZE, 8, 0, 0, 256);

    sass_register_kernel("vec_mul", sass_code_vec_mul,
                         SASS_VEC_MUL_SIZE, 8, 0, 0, 256);

    sass_register_kernel("silu_mul", sass_code_silu_mul,
                         SASS_SILU_MUL_SIZE, 12, 0, 0, 256);

    sass_register_kernel("add_inplace", sass_code_add_inplace,
                         SASS_ADD_INPLACE_SIZE, 8, 0, 0, 256);

    serial_puts("[SASS] Registered ");
    serial_putdec(sass_state.count);
    serial_puts(" kernels: ");
    for (uint32_t i = 0; i < sass_state.count; i++) {
        if (i > 0) serial_puts(", ");
        serial_puts(sass_state.kernels[i].name);
        serial_puts("(");
        serial_putdec(sass_state.kernels[i].code_size);
        serial_puts("B)");
    }
    serial_puts("\n");

    /* Dump instruction details for verification */
    serial_puts("[SASS] Instruction dump (nop kernel):\n");
    const sass_insn_t *insns = (const sass_insn_t *)sass_code_nop;
    uint32_t n_insns = sizeof(sass_code_nop) / SASS_INSN_SIZE;
    for (uint32_t i = 0; i < n_insns && i < 4; i++) {
        serial_puts("[SASS]   [");
        serial_putdec(i);
        serial_puts("] opcode=0x");
        serial_puthex(insns[i].opcode, 16);
        serial_puts(" ctrl=0x");
        serial_puthex(insns[i].control, 16);
        serial_puts("\n");
    }

    /* ── Upload all kernels to VRAM ── */

    if (p->vram_size_mb > 0) {
        uint32_t uploaded = 0;
        for (uint32_t i = 0; i < sass_state.count; i++) {
            if (sass_upload_kernel(&sass_state.kernels[i]) == 0)
                uploaded++;
        }
        serial_puts("[SASS] Uploaded ");
        serial_putdec(uploaded);
        serial_puts("/");
        serial_putdec(sass_state.count);
        serial_puts(" kernels to VRAM\n");
    } else {
        serial_puts("[SASS] No VRAM detected, kernel upload skipped\n");
    }

    sass_state.initialized = true;

    /* ── Smoke test ── */
    sass_smoke_test();

    serial_puts("[SASS] == X37 complete ==\n\n");

    fb_puts(" SASS: ");
    fb_putdec(sass_state.count);
    fb_puts(" kernels (");
    fb_putdec(sass_state.vram_next - sass_state.vram_base);
    fb_puts("B VRAM)\n");

    return 0;
}

/* ══════════════════════════════════════════════════════════
 *  X39: GPU Tensor Ops — Store Test + Vec Add
 *
 *  sass_store_test():
 *    Dispatches store_pattern kernel (1 thread), verifies
 *    0xCAFEBABE written to VRAM via PRAMIN readback.
 *    Proves: GMMU page table → compute dispatch → STG → VRAM.
 *
 *  sass_patch_vec_add():
 *    Patches src_a/src_b/dst addresses into vec_add_f32 kernel
 *    binary, re-uploads to VRAM. Enables data-driven dispatch.
 * ══════════════════════════════════════════════════════════ */

int sass_store_test(void)
{
    serial_puts("[SASS] -- Store test: write 0xCAFEBABE to VRAM --\n");

    sass_kernel_t *k = sass_get_kernel("store_pattern");
    if (!k || !k->uploaded) {
        serial_puts("[SASS] store_pattern kernel not available\n");
        return -1;
    }

    gpu_probe_t *p = gpu_get_probe();
    if (!p || !p->present || p->vram_size_mb == 0)
        return -1;

    /* Target address: VRAM+256MB+1MB = 0x10100000 (identity-mapped via GMMU) */
    uint64_t target_vram = 0x10100000;

    /* Clear target via PRAMIN */
    uint32_t saved_window = gpu_reg_read(NV_PBUS_BAR0_WINDOW);
    gpu_reg_write(NV_PBUS_BAR0_WINDOW, (uint32_t)(target_vram >> 16));
    wmb();
    uint32_t pramin_off = (uint32_t)(target_vram & 0xFFFF);
    gpu_reg_write(NV_PRAMIN_BASE + pramin_off, 0x00000000);
    wmb();

    /* Verify cleared */
    rmb();
    uint32_t before = gpu_reg_read(NV_PRAMIN_BASE + pramin_off);
    serial_puts("[SASS] VRAM@0x");
    serial_puthex(target_vram, 8);
    serial_puts(" before: 0x");
    serial_puthex(before, 8);
    serial_puts("\n");

    gpu_reg_write(NV_PBUS_BAR0_WINDOW, saved_window);
    wmb();

    /* Allocate semaphore */
    uint32_t *sem = (uint32_t *)mem_alloc_aligned(4096, 4096);
    if (!sem) return -1;
    *sem = 0;
    wmb();
    uint64_t sem_phys = (uint64_t)(uintptr_t)sem;

    /* Dispatch store_pattern kernel */
    compute_dispatch_t desc;
    memset(&desc, 0, sizeof(desc));
    desc.program_addr   = k->vram_addr;
    desc.grid_x         = 1;
    desc.grid_y         = 1;
    desc.grid_z         = 1;
    desc.block_x        = 1;
    desc.block_y        = 1;
    desc.block_z        = 1;
    desc.register_count = k->register_count;
    desc.sem_addr       = sem_phys;
    desc.sem_payload    = 0x5705E5E7;

    serial_puts("[SASS] Dispatching store_pattern: prog=0x");
    serial_puthex(k->vram_addr, 8);
    serial_puts("\n");

    int ret = gsp_compute_dispatch(&desc);
    if (ret < 0) {
        serial_puts("[SASS] Dispatch failed\n");
        return -1;
    }

    /* Wait for completion */
    ret = gsp_compute_wait(sem_phys, 0x5705E5E7, 500);

    /* Read back target via PRAMIN */
    saved_window = gpu_reg_read(NV_PBUS_BAR0_WINDOW);
    gpu_reg_write(NV_PBUS_BAR0_WINDOW, (uint32_t)(target_vram >> 16));
    wmb();
    rmb();
    uint32_t after = gpu_reg_read(NV_PRAMIN_BASE + pramin_off);
    gpu_reg_write(NV_PBUS_BAR0_WINDOW, saved_window);
    wmb();

    serial_puts("[SASS] VRAM@0x");
    serial_puthex(target_vram, 8);
    serial_puts(" after: 0x");
    serial_puthex(after, 8);
    serial_puts("\n");

    if (after == 0xCAFEBABE) {
        serial_puts("[SASS] *** STORE TEST PASSED! GMMU+Compute+STG works! ***\n");
        fb_puts_color(" SASS: store test PASS!\n", 0x0000FF00);
        return 0;
    }

    if (ret == 0)
        serial_puts("[SASS] Kernel completed but VRAM not written (GMMU or STG issue)\n");
    else
        serial_puts("[SASS] Store test pending — needs full GSP boot chain\n");

    return -1;
}

int sass_patch_vec_add(uint32_t src_a, uint32_t src_b, uint32_t dst)
{
    /* Patch MOV immediate fields in vec_add_f32 binary */
    sass_code_vec_add_f32[VEC_ADD_PATCH_SRC_A + 0] = (src_a >>  0) & 0xFF;
    sass_code_vec_add_f32[VEC_ADD_PATCH_SRC_A + 1] = (src_a >>  8) & 0xFF;
    sass_code_vec_add_f32[VEC_ADD_PATCH_SRC_A + 2] = (src_a >> 16) & 0xFF;
    sass_code_vec_add_f32[VEC_ADD_PATCH_SRC_A + 3] = (src_a >> 24) & 0xFF;

    sass_code_vec_add_f32[VEC_ADD_PATCH_SRC_B + 0] = (src_b >>  0) & 0xFF;
    sass_code_vec_add_f32[VEC_ADD_PATCH_SRC_B + 1] = (src_b >>  8) & 0xFF;
    sass_code_vec_add_f32[VEC_ADD_PATCH_SRC_B + 2] = (src_b >> 16) & 0xFF;
    sass_code_vec_add_f32[VEC_ADD_PATCH_SRC_B + 3] = (src_b >> 24) & 0xFF;

    sass_code_vec_add_f32[VEC_ADD_PATCH_DST + 0] = (dst >>  0) & 0xFF;
    sass_code_vec_add_f32[VEC_ADD_PATCH_DST + 1] = (dst >>  8) & 0xFF;
    sass_code_vec_add_f32[VEC_ADD_PATCH_DST + 2] = (dst >> 16) & 0xFF;
    sass_code_vec_add_f32[VEC_ADD_PATCH_DST + 3] = (dst >> 24) & 0xFF;

    /* Re-upload patched kernel to VRAM */
    sass_kernel_t *k = sass_get_kernel("vec_add_f32");
    if (!k) return -1;
    k->uploaded = false;
    return sass_upload_kernel(k);
}
