#include "venus_real.h"

extern void *memset(void *, int, unsigned long);
extern void *memcpy(void *, const void *, unsigned long);
extern void *malloc(unsigned long);
extern void free(void *);
extern int strcmp(const char *, const char *);

#define VN_CMD_GET_PHYSICAL_DEVICE_PROPERTIES 6u
#define VN_CMD_GET_QUEUE_FAMILY_PROPERTIES 7u
#define VN_CMD_GET_PHYSICAL_DEVICE_FEATURES 3u
#define VN_CMD_GET_PHYSICAL_DEVICE_MEMORY_PROPERTIES 8u
#define VN_CMD_ENUMERATE_DEVICE_EXTENSION_PROPERTIES 14u
#define VN_CMD_GET_PHYSICAL_DEVICE_FEATURES_2 147u
#define VN_CMD_GET_PHYSICAL_DEVICE_PROPERTIES_2 148u
#define VN_CMD_GET_PHYSICAL_DEVICE_FORMAT_PROPERTIES_2 149u
#define VN_CMD_GET_PHYSICAL_DEVICE_IMAGE_FORMAT_PROPERTIES_2 150u
#define VN_CMD_GET_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2 152u
#define VN_CMD_GET_PHYSICAL_DEVICE_CALIBRATEABLE_TIME_DOMAINS_EXT 235u
#define VN_COMMAND_GENERATE_REPLY 1u
#define VN_PROPERTIES_REPLY_SIZE 1024u

struct wire_decoder {
    const uint8_t *data;
    uint32_t capacity;
    uint32_t offset;
    int failed;
};

struct wire_encoder {
    uint8_t *data;
    uint32_t capacity;
    uint32_t offset;
    int failed;
};

static void encode_bytes(struct wire_encoder *enc, const void *src,
                         uint32_t size)
{
    if (enc->offset > enc->capacity || size > enc->capacity - enc->offset) {
        enc->failed = 1;
        return;
    }
    if (size)
        memcpy(enc->data + enc->offset, src, size);
    enc->offset += size;
}

static void encode_u32(struct wire_encoder *enc, uint32_t value)
{
    encode_bytes(enc, &value, sizeof(value));
}

static void encode_u64(struct wire_encoder *enc, uint64_t value)
{
    encode_bytes(enc, &value, sizeof(value));
}

static void decode_bytes(struct wire_decoder *dec, void *dst, uint32_t size)
{
    if (dec->offset > dec->capacity || size > dec->capacity - dec->offset) {
        dec->failed = 1;
        return;
    }
    if (size)
        memcpy(dst, dec->data + dec->offset, size);
    dec->offset += size;
}

static uint64_t decode_array_size(struct wire_decoder *dec,
                                  uint64_t expected)
{
    uint64_t count = 0;
    decode_bytes(dec, &count, sizeof(count));
    if (count != expected)
        dec->failed = 1;
    return count;
}

#define D32(field) decode_bytes(dec, &(field), 4)
#define D64(field) decode_bytes(dec, &(field), 8)
#define DARRAY(field, count) do { \
    if (decode_array_size(dec, (count)) == (count)) \
        decode_bytes(dec, (field), sizeof((field)[0]) * (count)); \
} while (0)

/* Field order is generated by Mesa venus-protocol for
 * VkPhysicalDeviceLimits. */
static void decode_limits(struct wire_decoder *dec,
                          VkPhysicalDeviceLimits *limits)
{
    D32(limits->maxImageDimension1D);
    D32(limits->maxImageDimension2D);
    D32(limits->maxImageDimension3D);
    D32(limits->maxImageDimensionCube);
    D32(limits->maxImageArrayLayers);
    D32(limits->maxTexelBufferElements);
    D32(limits->maxUniformBufferRange);
    D32(limits->maxStorageBufferRange);
    D32(limits->maxPushConstantsSize);
    D32(limits->maxMemoryAllocationCount);
    D32(limits->maxSamplerAllocationCount);
    D64(limits->bufferImageGranularity);
    D64(limits->sparseAddressSpaceSize);
    D32(limits->maxBoundDescriptorSets);
    D32(limits->maxPerStageDescriptorSamplers);
    D32(limits->maxPerStageDescriptorUniformBuffers);
    D32(limits->maxPerStageDescriptorStorageBuffers);
    D32(limits->maxPerStageDescriptorSampledImages);
    D32(limits->maxPerStageDescriptorStorageImages);
    D32(limits->maxPerStageDescriptorInputAttachments);
    D32(limits->maxPerStageResources);
    D32(limits->maxDescriptorSetSamplers);
    D32(limits->maxDescriptorSetUniformBuffers);
    D32(limits->maxDescriptorSetUniformBuffersDynamic);
    D32(limits->maxDescriptorSetStorageBuffers);
    D32(limits->maxDescriptorSetStorageBuffersDynamic);
    D32(limits->maxDescriptorSetSampledImages);
    D32(limits->maxDescriptorSetStorageImages);
    D32(limits->maxDescriptorSetInputAttachments);
    D32(limits->maxVertexInputAttributes);
    D32(limits->maxVertexInputBindings);
    D32(limits->maxVertexInputAttributeOffset);
    D32(limits->maxVertexInputBindingStride);
    D32(limits->maxVertexOutputComponents);
    D32(limits->maxTessellationGenerationLevel);
    D32(limits->maxTessellationPatchSize);
    D32(limits->maxTessellationControlPerVertexInputComponents);
    D32(limits->maxTessellationControlPerVertexOutputComponents);
    D32(limits->maxTessellationControlPerPatchOutputComponents);
    D32(limits->maxTessellationControlTotalOutputComponents);
    D32(limits->maxTessellationEvaluationInputComponents);
    D32(limits->maxTessellationEvaluationOutputComponents);
    D32(limits->maxGeometryShaderInvocations);
    D32(limits->maxGeometryInputComponents);
    D32(limits->maxGeometryOutputComponents);
    D32(limits->maxGeometryOutputVertices);
    D32(limits->maxGeometryTotalOutputComponents);
    D32(limits->maxFragmentInputComponents);
    D32(limits->maxFragmentOutputAttachments);
    D32(limits->maxFragmentDualSrcAttachments);
    D32(limits->maxFragmentCombinedOutputResources);
    D32(limits->maxComputeSharedMemorySize);
    DARRAY(limits->maxComputeWorkGroupCount, 3);
    D32(limits->maxComputeWorkGroupInvocations);
    DARRAY(limits->maxComputeWorkGroupSize, 3);
    D32(limits->subPixelPrecisionBits);
    D32(limits->subTexelPrecisionBits);
    D32(limits->mipmapPrecisionBits);
    D32(limits->maxDrawIndexedIndexValue);
    D32(limits->maxDrawIndirectCount);
    D32(limits->maxSamplerLodBias);
    D32(limits->maxSamplerAnisotropy);
    D32(limits->maxViewports);
    DARRAY(limits->maxViewportDimensions, 2);
    DARRAY(limits->viewportBoundsRange, 2);
    D32(limits->viewportSubPixelBits);
    D64(limits->minMemoryMapAlignment);
    D64(limits->minTexelBufferOffsetAlignment);
    D64(limits->minUniformBufferOffsetAlignment);
    D64(limits->minStorageBufferOffsetAlignment);
    D32(limits->minTexelOffset);
    D32(limits->maxTexelOffset);
    D32(limits->minTexelGatherOffset);
    D32(limits->maxTexelGatherOffset);
    D32(limits->minInterpolationOffset);
    D32(limits->maxInterpolationOffset);
    D32(limits->subPixelInterpolationOffsetBits);
    D32(limits->maxFramebufferWidth);
    D32(limits->maxFramebufferHeight);
    D32(limits->maxFramebufferLayers);
    D32(limits->framebufferColorSampleCounts);
    D32(limits->framebufferDepthSampleCounts);
    D32(limits->framebufferStencilSampleCounts);
    D32(limits->framebufferNoAttachmentsSampleCounts);
    D32(limits->maxColorAttachments);
    D32(limits->sampledImageColorSampleCounts);
    D32(limits->sampledImageIntegerSampleCounts);
    D32(limits->sampledImageDepthSampleCounts);
    D32(limits->sampledImageStencilSampleCounts);
    D32(limits->storageImageSampleCounts);
    D32(limits->maxSampleMaskWords);
    D32(limits->timestampComputeAndGraphics);
    D32(limits->timestampPeriod);
    D32(limits->maxClipDistances);
    D32(limits->maxCullDistances);
    D32(limits->maxCombinedClipAndCullDistances);
    D32(limits->discreteQueuePriorities);
    DARRAY(limits->pointSizeRange, 2);
    DARRAY(limits->lineWidthRange, 2);
    D32(limits->pointSizeGranularity);
    D32(limits->lineWidthGranularity);
    D32(limits->strictLines);
    D32(limits->standardSampleLocations);
    D64(limits->optimalBufferCopyOffsetAlignment);
    D64(limits->optimalBufferCopyRowPitchAlignment);
    D64(limits->nonCoherentAtomSize);
}

static void decode_properties(struct wire_decoder *dec,
                              VkPhysicalDeviceProperties *properties)
{
    D32(properties->apiVersion);
    D32(properties->driverVersion);
    D32(properties->vendorID);
    D32(properties->deviceID);
    D32(properties->deviceType);
    DARRAY(properties->deviceName, VK_MAX_PHYSICAL_DEVICE_NAME_SIZE);
    DARRAY(properties->pipelineCacheUUID, VK_UUID_SIZE);
    decode_limits(dec, &properties->limits);
    D32(properties->sparseProperties.residencyStandard2DBlockShape);
    D32(properties->sparseProperties.residencyStandard2DMultisampleBlockShape);
    D32(properties->sparseProperties.residencyStandard3DBlockShape);
    D32(properties->sparseProperties.residencyAlignedMipSize);
    D32(properties->sparseProperties.residencyNonResidentStrict);
}

VKAPI_ATTR void VKAPI_CALL
venus_real_GetPhysicalDeviceProperties(VkPhysicalDevice physical_device,
                                       VkPhysicalDeviceProperties *properties)
{
    if (!physical_device || !properties)
        return;
    memset(properties, 0, sizeof(*properties));

    struct venus_physical_device_real *physical =
        (struct venus_physical_device_real *)physical_device;
    struct venus_instance_real *instance = physical->instance;
    uint8_t command[24];
    uint32_t command_type = VN_CMD_GET_PHYSICAL_DEVICE_PROPERTIES;
    uint32_t command_flags = VN_COMMAND_GENERATE_REPLY;
    uint64_t present = 1;
    memcpy(command, &command_type, 4);
    memcpy(command + 4, &command_flags, 4);
    memcpy(command + 8, &physical->object_id, 8);
    memcpy(command + 16, &present, 8);

    uint8_t reply[VN_PROPERTIES_REPLY_SIZE];
    memset(reply, 0, sizeof(reply));
    if (!instance || !instance->wire ||
        venus_wire_call(instance->wire, command, sizeof(command), reply,
                        sizeof(reply)) < 0)
        return;

    struct wire_decoder dec = {
        .data = reply,
        .capacity = sizeof(reply),
    };
    uint32_t returned_command = 0;
    uint64_t returned_present = 0;
    decode_bytes(&dec, &returned_command, sizeof(returned_command));
    decode_bytes(&dec, &returned_present, sizeof(returned_present));
    if (returned_command != VN_CMD_GET_PHYSICAL_DEVICE_PROPERTIES ||
        !returned_present) {
        memset(properties, 0, sizeof(*properties));
        return;
    }
    decode_properties(&dec, properties);
    if (dec.failed)
        memset(properties, 0, sizeof(*properties));
}

static int get_host_queue_families(
    struct venus_physical_device_real *physical, uint32_t *count,
    VkQueueFamilyProperties *properties)
{
    uint32_t capacity = properties ? *count : 0;
    if (capacity > 256u)
        return -1;
    uint32_t reply_size = 24u + capacity * 24u;
    uint8_t *reply = malloc(reply_size);
    if (!reply)
        return -1;

    uint8_t command[36];
    uint32_t command_type = VN_CMD_GET_QUEUE_FAMILY_PROPERTIES;
    uint32_t command_flags = VN_COMMAND_GENERATE_REPLY;
    uint64_t present = 1;
    uint64_t array_size = capacity;
    memcpy(command, &command_type, 4);
    memcpy(command + 4, &command_flags, 4);
    memcpy(command + 8, &physical->object_id, 8);
    memcpy(command + 16, &present, 8);
    memcpy(command + 24, &capacity, 4);
    memcpy(command + 28, &array_size, 8);

    memset(reply, 0, reply_size);
    if (venus_wire_call(physical->instance->wire, command, sizeof(command),
                        reply, reply_size) < 0) {
        free(reply);
        return -1;
    }

    struct wire_decoder dec_storage = {
        .data = reply,
        .capacity = reply_size,
    };
    struct wire_decoder *dec = &dec_storage;
    uint32_t returned_command = 0;
    uint64_t count_present = 0;
    uint32_t returned_count = 0;
    D32(returned_command);
    D64(count_present);
    D32(returned_count);
    uint64_t returned_array_size = 0;
    decode_bytes(dec, &returned_array_size, sizeof(returned_array_size));
    if (returned_command != VN_CMD_GET_QUEUE_FAMILY_PROPERTIES ||
        !count_present || returned_array_size > capacity ||
        returned_array_size != (properties ? returned_count : 0))
        dec->failed = 1;

    for (uint32_t i = 0; i < returned_array_size && !dec->failed; i++) {
        D32(properties[i].queueFlags);
        D32(properties[i].queueCount);
        D32(properties[i].timestampValidBits);
        D32(properties[i].minImageTransferGranularity.width);
        D32(properties[i].minImageTransferGranularity.height);
        D32(properties[i].minImageTransferGranularity.depth);
    }
    free(reply);
    if (dec->failed)
        return -1;
    *count = returned_count;
    return 0;
}

static int init_queue_families(struct venus_physical_device_real *physical)
{
    if (physical->queue_families_initialized)
        return 0;
    uint32_t count = 0;
    if (get_host_queue_families(physical, &count, 0) < 0)
        return -1;
    if (!count) {
        physical->queue_families_initialized = 1;
        return 0;
    }

    VkQueueFamilyProperties *properties =
        malloc((unsigned long)count * sizeof(*properties));
    if (!properties)
        return -1;
    memset(properties, 0, (unsigned long)count * sizeof(*properties));
    uint32_t returned_count = count;
    if (get_host_queue_families(physical, &returned_count, properties) < 0 ||
        returned_count > count) {
        free(properties);
        return -1;
    }
    physical->queue_family_properties = properties;
    physical->queue_family_count = returned_count;
    physical->queue_families_initialized = 1;
    return 0;
}

VKAPI_ATTR void VKAPI_CALL
venus_real_GetPhysicalDeviceQueueFamilyProperties(
    VkPhysicalDevice physical_device, uint32_t *property_count,
    VkQueueFamilyProperties *properties)
{
    if (!physical_device || !property_count)
        return;
    struct venus_physical_device_real *physical =
        (struct venus_physical_device_real *)physical_device;
    if (init_queue_families(physical) < 0) {
        *property_count = 0;
        return;
    }
    if (!properties) {
        *property_count = physical->queue_family_count;
        return;
    }
    uint32_t written = *property_count < physical->queue_family_count
        ? *property_count : physical->queue_family_count;
    memcpy(properties, physical->queue_family_properties,
           (unsigned long)written * sizeof(*properties));
    *property_count = written;
}

static int begin_physical_query(struct venus_physical_device_real *physical,
                                uint32_t command_type, const void *suffix,
                                uint32_t suffix_size, uint8_t *reply,
                                uint32_t reply_size)
{
    uint8_t command[40];
    uint32_t command_size = 24u + suffix_size;
    if (command_size > sizeof(command))
        return -1;
    uint32_t command_flags = VN_COMMAND_GENERATE_REPLY;
    uint64_t present = 1;
    memcpy(command, &command_type, 4);
    memcpy(command + 4, &command_flags, 4);
    memcpy(command + 8, &physical->object_id, 8);
    memcpy(command + 16, &present, 8);
    if (suffix_size)
        memcpy(command + 24, suffix, suffix_size);
    memset(reply, 0, reply_size);
    return venus_wire_call(physical->instance->wire, command, command_size,
                           reply, reply_size);
}

VKAPI_ATTR void VKAPI_CALL
venus_real_GetPhysicalDeviceFeatures(VkPhysicalDevice physical_device,
                                     VkPhysicalDeviceFeatures *features)
{
    if (!physical_device || !features)
        return;
    memset(features, 0, sizeof(*features));
    struct venus_physical_device_real *physical =
        (struct venus_physical_device_real *)physical_device;
    uint8_t reply[12u + sizeof(*features)];
    if (begin_physical_query(physical,
                             VN_CMD_GET_PHYSICAL_DEVICE_FEATURES,
                             0, 0, reply, sizeof(reply)) < 0)
        return;

    struct wire_decoder dec_storage = {
        .data = reply,
        .capacity = sizeof(reply),
    };
    struct wire_decoder *dec = &dec_storage;
    uint32_t returned_command = 0;
    uint64_t present = 0;
    D32(returned_command);
    D64(present);
    if (returned_command == VN_CMD_GET_PHYSICAL_DEVICE_FEATURES && present)
        decode_bytes(dec, features, sizeof(*features));
    if (dec->failed ||
        returned_command != VN_CMD_GET_PHYSICAL_DEVICE_FEATURES || !present)
        memset(features, 0, sizeof(*features));
    /* Sparse resources require buffer/image and sparse-bind commands that the
     * guest ICD does not expose yet. Do not leak the renderer's support. */
    features->sparseBinding = VK_FALSE;
    features->sparseResidencyBuffer = VK_FALSE;
    features->sparseResidencyImage2D = VK_FALSE;
    features->sparseResidencyImage3D = VK_FALSE;
    features->sparseResidency2Samples = VK_FALSE;
    features->sparseResidency4Samples = VK_FALSE;
    features->sparseResidency8Samples = VK_FALSE;
    features->sparseResidency16Samples = VK_FALSE;
    features->sparseResidencyAliased = VK_FALSE;
}

VKAPI_ATTR void VKAPI_CALL
venus_real_GetPhysicalDeviceMemoryProperties(
    VkPhysicalDevice physical_device,
    VkPhysicalDeviceMemoryProperties *properties)
{
    if (!physical_device || !properties)
        return;
    memset(properties, 0, sizeof(*properties));
    struct venus_physical_device_real *physical =
        (struct venus_physical_device_real *)physical_device;
    const uint64_t suffix[2] = {
        VK_MAX_MEMORY_TYPES,
        VK_MAX_MEMORY_HEAPS,
    };
    uint8_t reply[484];
    if (begin_physical_query(
            physical, VN_CMD_GET_PHYSICAL_DEVICE_MEMORY_PROPERTIES,
            suffix, sizeof(suffix), reply, sizeof(reply)) < 0)
        return;

    struct wire_decoder dec_storage = {
        .data = reply,
        .capacity = sizeof(reply),
    };
    struct wire_decoder *dec = &dec_storage;
    uint32_t returned_command = 0;
    uint64_t present = 0;
    D32(returned_command);
    D64(present);
    D32(properties->memoryTypeCount);
    if (decode_array_size(dec, VK_MAX_MEMORY_TYPES) == VK_MAX_MEMORY_TYPES) {
        for (uint32_t i = 0; i < VK_MAX_MEMORY_TYPES; i++) {
            D32(properties->memoryTypes[i].propertyFlags);
            D32(properties->memoryTypes[i].heapIndex);
        }
    }
    D32(properties->memoryHeapCount);
    if (decode_array_size(dec, VK_MAX_MEMORY_HEAPS) == VK_MAX_MEMORY_HEAPS) {
        for (uint32_t i = 0; i < VK_MAX_MEMORY_HEAPS; i++) {
            D64(properties->memoryHeaps[i].size);
            D32(properties->memoryHeaps[i].flags);
        }
    }
    if (dec->failed ||
        returned_command != VN_CMD_GET_PHYSICAL_DEVICE_MEMORY_PROPERTIES ||
        !present || properties->memoryTypeCount > VK_MAX_MEMORY_TYPES ||
        properties->memoryHeapCount > VK_MAX_MEMORY_HEAPS)
        memset(properties, 0, sizeof(*properties));
}

static int begin_output_struct_query(
    struct venus_physical_device_real *physical, uint32_t command_type,
    const void *command_extra, uint32_t command_extra_size,
    VkStructureType root_type, VkStructureType extension_type,
    const void *root_partial, uint32_t root_partial_size,
    uint8_t *reply, uint32_t reply_size, struct wire_decoder *dec)
{
    uint8_t command[96];
    struct wire_encoder enc = {
        .data = command,
        .capacity = sizeof(command),
    };
    encode_u32(&enc, command_type);
    encode_u32(&enc, VN_COMMAND_GENERATE_REPLY);
    encode_u64(&enc, physical->object_id);
    encode_bytes(&enc, command_extra, command_extra_size);
    encode_u64(&enc, 1); /* root output pointer */
    encode_u32(&enc, (uint32_t)root_type);
    if (extension_type) {
        encode_u64(&enc, 1);
        encode_u32(&enc, (uint32_t)extension_type);
        encode_u64(&enc, 0); /* extension pNext */
    } else {
        encode_u64(&enc, 0);
    }
    encode_bytes(&enc, root_partial, root_partial_size);
    if (enc.failed)
        return -1;

    memset(reply, 0, reply_size);
    if (venus_wire_call(physical->instance->wire, command, enc.offset,
                        reply, reply_size) < 0)
        return -1;

    dec->data = reply;
    dec->capacity = reply_size;
    dec->offset = 0;
    dec->failed = 0;
    uint32_t returned_command = 0;
    uint64_t present = 0;
    uint32_t returned_type = 0;
    decode_bytes(dec, &returned_command, sizeof(returned_command));
    decode_bytes(dec, &present, sizeof(present));
    decode_bytes(dec, &returned_type, sizeof(returned_type));
    if (returned_command != command_type || !present ||
        returned_type != (uint32_t)root_type)
        dec->failed = 1;

    uint64_t extension_present = 0;
    decode_bytes(dec, &extension_present, sizeof(extension_present));
    if (extension_type) {
        uint32_t returned_extension_type = 0;
        uint64_t child_present = 0;
        decode_bytes(dec, &returned_extension_type,
                     sizeof(returned_extension_type));
        decode_bytes(dec, &child_present, sizeof(child_present));
        if (!extension_present ||
            returned_extension_type != (uint32_t)extension_type ||
            child_present)
            dec->failed = 1;
    } else if (extension_present) {
        dec->failed = 1;
    }
    return dec->failed ? -1 : 0;
}

static void decode_vulkan11_properties(
    struct wire_decoder *dec, VkPhysicalDeviceVulkan11Properties *out)
{
    DARRAY(out->deviceUUID, VK_UUID_SIZE);
    DARRAY(out->driverUUID, VK_UUID_SIZE);
    DARRAY(out->deviceLUID, VK_LUID_SIZE);
    D32(out->deviceNodeMask);
    D32(out->deviceLUIDValid);
    D32(out->subgroupSize);
    D32(out->subgroupSupportedStages);
    D32(out->subgroupSupportedOperations);
    D32(out->subgroupQuadOperationsInAllStages);
    D32(out->pointClippingBehavior);
    D32(out->maxMultiviewViewCount);
    D32(out->maxMultiviewInstanceIndex);
    D32(out->protectedNoFault);
    D32(out->maxPerSetDescriptors);
    D64(out->maxMemoryAllocationSize);
}

static void decode_vulkan12_properties(
    struct wire_decoder *dec, VkPhysicalDeviceVulkan12Properties *out)
{
    D32(out->driverID);
    DARRAY(out->driverName, VK_MAX_DRIVER_NAME_SIZE);
    DARRAY(out->driverInfo, VK_MAX_DRIVER_INFO_SIZE);
    decode_bytes(dec, &out->conformanceVersion,
                 sizeof(out->conformanceVersion));
    decode_bytes(dec, &out->denormBehaviorIndependence,
                 (uint32_t)((uint8_t *)&out->maxTimelineSemaphoreValueDifference -
                            (uint8_t *)&out->denormBehaviorIndependence));
    D64(out->maxTimelineSemaphoreValueDifference);
    D32(out->framebufferIntegerColorSampleCounts);
}

static void decode_vulkan13_properties(
    struct wire_decoder *dec, VkPhysicalDeviceVulkan13Properties *out)
{
    decode_bytes(dec, &out->minSubgroupSize,
                 (uint32_t)((uint8_t *)&out->storageTexelBufferOffsetAlignmentBytes -
                            (uint8_t *)&out->minSubgroupSize));
    D64(out->storageTexelBufferOffsetAlignmentBytes);
    D32(out->storageTexelBufferOffsetSingleTexelAlignment);
    D64(out->uniformTexelBufferOffsetAlignmentBytes);
    D32(out->uniformTexelBufferOffsetSingleTexelAlignment);
    D64(out->maxBufferSize);
}

static int decode_property_extension(struct wire_decoder *dec,
                                     VkBaseOutStructure *out)
{
    switch (out->sType) {
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_PROPERTIES:
        decode_vulkan11_properties(
            dec, (VkPhysicalDeviceVulkan11Properties *)out);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_PROPERTIES:
        decode_vulkan12_properties(
            dec, (VkPhysicalDeviceVulkan12Properties *)out);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_PROPERTIES:
        decode_vulkan13_properties(
            dec, (VkPhysicalDeviceVulkan13Properties *)out);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CONSERVATIVE_RASTERIZATION_PROPERTIES_EXT: {
        VkPhysicalDeviceConservativeRasterizationPropertiesEXT *p =
            (VkPhysicalDeviceConservativeRasterizationPropertiesEXT *)out;
        decode_bytes(dec, &p->primitiveOverestimationSize,
                     3u * sizeof(float) + 6u * sizeof(VkBool32));
        break;
    }
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CUSTOM_BORDER_COLOR_PROPERTIES_EXT:
        D32(((VkPhysicalDeviceCustomBorderColorPropertiesEXT *)out)->
                maxCustomBorderColorSamplers);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTENDED_DYNAMIC_STATE_3_PROPERTIES_EXT:
        D32(((VkPhysicalDeviceExtendedDynamicState3PropertiesEXT *)out)->
                dynamicPrimitiveTopologyUnrestricted);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GRAPHICS_PIPELINE_LIBRARY_PROPERTIES_EXT: {
        VkPhysicalDeviceGraphicsPipelineLibraryPropertiesEXT *p =
            (VkPhysicalDeviceGraphicsPipelineLibraryPropertiesEXT *)out;
        D32(p->graphicsPipelineLibraryFastLinking);
        D32(p->graphicsPipelineLibraryIndependentInterpolationDecoration);
        break;
    }
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_LINE_RASTERIZATION_PROPERTIES:
        D32(((VkPhysicalDeviceLineRasterizationProperties *)out)->
                lineSubPixelPrecisionBits);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ROBUSTNESS_2_PROPERTIES_EXT: {
        VkPhysicalDeviceRobustness2PropertiesEXT *p =
            (VkPhysicalDeviceRobustness2PropertiesEXT *)out;
        D64(p->robustStorageBufferAccessSizeAlignment);
        D64(p->robustUniformBufferAccessSizeAlignment);
        break;
    }
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TRANSFORM_FEEDBACK_PROPERTIES_EXT: {
        VkPhysicalDeviceTransformFeedbackPropertiesEXT *p =
            (VkPhysicalDeviceTransformFeedbackPropertiesEXT *)out;
        D32(p->maxTransformFeedbackStreams);
        D32(p->maxTransformFeedbackBuffers);
        D64(p->maxTransformFeedbackBufferSize);
        decode_bytes(dec, &p->maxTransformFeedbackStreamDataSize,
                     7u * sizeof(uint32_t));
        break;
    }
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_PROPERTIES_EXT:
        D32(((VkPhysicalDeviceVertexAttributeDivisorPropertiesEXT *)out)->
                maxVertexAttribDivisor);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_5_PROPERTIES: {
        VkPhysicalDeviceMaintenance5Properties *p =
            (VkPhysicalDeviceMaintenance5Properties *)out;
        decode_bytes(dec,
                     &p->earlyFragmentMultisampleCoverageAfterSampleCounting,
                     6u * sizeof(VkBool32));
        break;
    }
    default:
        return 0;
    }
    return 1;
}

VKAPI_ATTR void VKAPI_CALL
venus_real_GetPhysicalDeviceProperties2(
    VkPhysicalDevice physical_device, VkPhysicalDeviceProperties2 *properties)
{
    if (!physical_device || !properties)
        return;
    venus_real_GetPhysicalDeviceProperties(physical_device,
                                            &properties->properties);
    struct venus_physical_device_real *physical =
        (struct venus_physical_device_real *)physical_device;
    for (VkBaseOutStructure *out = (VkBaseOutStructure *)properties->pNext;
         out; out = out->pNext) {
        uint8_t reply[2048];
        struct wire_decoder dec;
        switch (out->sType) {
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_PROPERTIES:
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_PROPERTIES:
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_PROPERTIES:
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CONSERVATIVE_RASTERIZATION_PROPERTIES_EXT:
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CUSTOM_BORDER_COLOR_PROPERTIES_EXT:
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTENDED_DYNAMIC_STATE_3_PROPERTIES_EXT:
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GRAPHICS_PIPELINE_LIBRARY_PROPERTIES_EXT:
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_LINE_RASTERIZATION_PROPERTIES:
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ROBUSTNESS_2_PROPERTIES_EXT:
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TRANSFORM_FEEDBACK_PROPERTIES_EXT:
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_PROPERTIES_EXT:
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_5_PROPERTIES:
            break;
        default:
            continue;
        }
        if (begin_output_struct_query(
                physical, VN_CMD_GET_PHYSICAL_DEVICE_PROPERTIES_2,
                0, 0, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2,
                out->sType, 0, 0, reply, sizeof(reply), &dec) == 0) {
            (void)decode_property_extension(&dec, out);
        }
    }
}

#define DECODE_BOOL_RANGE(type, value, first, last) do { \
    type *typed = (type *)(value); \
    decode_bytes(dec, &typed->first, \
        (uint32_t)((uint8_t *)&typed->last + sizeof(typed->last) - \
                   (uint8_t *)&typed->first)); \
} while (0)

static int decode_feature_extension(struct wire_decoder *dec,
                                    VkBaseOutStructure *out)
{
    switch (out->sType) {
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_FEATURES:
        DECODE_BOOL_RANGE(VkPhysicalDeviceVulkan11Features, out,
                          storageBuffer16BitAccess, shaderDrawParameters);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES:
        DECODE_BOOL_RANGE(VkPhysicalDeviceVulkan12Features, out,
                          samplerMirrorClampToEdge,
                          subgroupBroadcastDynamicId);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_FEATURES:
        DECODE_BOOL_RANGE(VkPhysicalDeviceVulkan13Features, out,
                          robustImageAccess, maintenance4);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ATTACHMENT_FEEDBACK_LOOP_LAYOUT_FEATURES_EXT:
        DECODE_BOOL_RANGE(VkPhysicalDeviceAttachmentFeedbackLoopLayoutFeaturesEXT,
                          out, attachmentFeedbackLoopLayout,
                          attachmentFeedbackLoopLayout);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CUSTOM_BORDER_COLOR_FEATURES_EXT:
        DECODE_BOOL_RANGE(VkPhysicalDeviceCustomBorderColorFeaturesEXT, out,
                          customBorderColors,
                          customBorderColorWithoutFormat);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_CLIP_ENABLE_FEATURES_EXT:
        DECODE_BOOL_RANGE(VkPhysicalDeviceDepthClipEnableFeaturesEXT, out,
                          depthClipEnable, depthClipEnable);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_BIAS_CONTROL_FEATURES_EXT:
        DECODE_BOOL_RANGE(VkPhysicalDeviceDepthBiasControlFeaturesEXT, out,
                          depthBiasControl, depthBiasExact);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTENDED_DYNAMIC_STATE_3_FEATURES_EXT:
        DECODE_BOOL_RANGE(VkPhysicalDeviceExtendedDynamicState3FeaturesEXT, out,
                          extendedDynamicState3TessellationDomainOrigin,
                          extendedDynamicState3ShadingRateImageEnable);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_SHADER_INTERLOCK_FEATURES_EXT:
        DECODE_BOOL_RANGE(VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT,
                          out, fragmentShaderSampleInterlock,
                          fragmentShaderShadingRateInterlock);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GRAPHICS_PIPELINE_LIBRARY_FEATURES_EXT:
        DECODE_BOOL_RANGE(VkPhysicalDeviceGraphicsPipelineLibraryFeaturesEXT,
                          out, graphicsPipelineLibrary,
                          graphicsPipelineLibrary);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_LINE_RASTERIZATION_FEATURES:
        DECODE_BOOL_RANGE(VkPhysicalDeviceLineRasterizationFeatures, out,
                          rectangularLines, stippledSmoothLines);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PRIORITY_FEATURES_EXT:
        DECODE_BOOL_RANGE(VkPhysicalDeviceMemoryPriorityFeaturesEXT, out,
                          memoryPriority, memoryPriority);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_NON_SEAMLESS_CUBE_MAP_FEATURES_EXT:
        DECODE_BOOL_RANGE(VkPhysicalDeviceNonSeamlessCubeMapFeaturesEXT, out,
                          nonSeamlessCubeMap, nonSeamlessCubeMap);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ROBUSTNESS_2_FEATURES_EXT:
        DECODE_BOOL_RANGE(VkPhysicalDeviceRobustness2FeaturesEXT, out,
                          robustBufferAccess2, nullDescriptor);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_MODULE_IDENTIFIER_FEATURES_EXT:
        DECODE_BOOL_RANGE(VkPhysicalDeviceShaderModuleIdentifierFeaturesEXT,
                          out, shaderModuleIdentifier,
                          shaderModuleIdentifier);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SWAPCHAIN_MAINTENANCE_1_FEATURES_EXT:
        DECODE_BOOL_RANGE(VkPhysicalDeviceSwapchainMaintenance1FeaturesEXT,
                          out, swapchainMaintenance1, swapchainMaintenance1);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TRANSFORM_FEEDBACK_FEATURES_EXT:
        DECODE_BOOL_RANGE(VkPhysicalDeviceTransformFeedbackFeaturesEXT, out,
                          transformFeedback, geometryStreams);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_FEATURES_EXT:
        DECODE_BOOL_RANGE(VkPhysicalDeviceVertexAttributeDivisorFeaturesEXT,
                          out, vertexAttributeInstanceRateDivisor,
                          vertexAttributeInstanceRateZeroDivisor);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_5_FEATURES:
        DECODE_BOOL_RANGE(VkPhysicalDeviceMaintenance5Features, out,
                          maintenance5, maintenance5);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PRESENT_ID_FEATURES_KHR:
        DECODE_BOOL_RANGE(VkPhysicalDevicePresentIdFeaturesKHR, out,
                          presentId, presentId);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PRESENT_WAIT_FEATURES_KHR:
        DECODE_BOOL_RANGE(VkPhysicalDevicePresentWaitFeaturesKHR, out,
                          presentWait, presentWait);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_POOL_OVERALLOCATION_FEATURES_NV:
        DECODE_BOOL_RANGE(VkPhysicalDeviceDescriptorPoolOverallocationFeaturesNV,
                          out, descriptorPoolOverallocation,
                          descriptorPoolOverallocation);
        break;
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RAW_ACCESS_CHAINS_FEATURES_NV:
        DECODE_BOOL_RANGE(VkPhysicalDeviceRawAccessChainsFeaturesNV, out,
                          shaderRawAccessChains, shaderRawAccessChains);
        break;
    default:
        return 0;
    }
    return 1;
}

VKAPI_ATTR void VKAPI_CALL
venus_real_GetPhysicalDeviceFeatures2(
    VkPhysicalDevice physical_device, VkPhysicalDeviceFeatures2 *features)
{
    if (!physical_device || !features)
        return;
    venus_real_GetPhysicalDeviceFeatures(physical_device, &features->features);
    struct venus_physical_device_real *physical =
        (struct venus_physical_device_real *)physical_device;
    for (VkBaseOutStructure *out = (VkBaseOutStructure *)features->pNext;
         out; out = out->pNext) {
        uint8_t reply[1024];
        struct wire_decoder dec_storage;
        struct wire_decoder *dec = &dec_storage;
        if (begin_output_struct_query(
                physical, VN_CMD_GET_PHYSICAL_DEVICE_FEATURES_2,
                0, 0, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2,
                out->sType, 0, 0, reply, sizeof(reply), dec) == 0)
            (void)decode_feature_extension(dec, out);
        if (out->sType ==
            VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GRAPHICS_PIPELINE_LIBRARY_FEATURES_EXT) {
            VkPhysicalDeviceGraphicsPipelineLibraryFeaturesEXT *feature =
                (VkPhysicalDeviceGraphicsPipelineLibraryFeaturesEXT *)out;
            feature->graphicsPipelineLibrary = VK_FALSE;
        }
    }
}

VKAPI_ATTR void VKAPI_CALL
venus_real_GetPhysicalDeviceMemoryProperties2(
    VkPhysicalDevice physical_device,
    VkPhysicalDeviceMemoryProperties2 *properties)
{
    if (!physical_device || !properties)
        return;
    venus_real_GetPhysicalDeviceMemoryProperties(
        physical_device, &properties->memoryProperties);
    struct venus_physical_device_real *physical =
        (struct venus_physical_device_real *)physical_device;
    for (VkBaseOutStructure *out = (VkBaseOutStructure *)properties->pNext;
         out; out = out->pNext) {
        if (out->sType !=
            VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_BUDGET_PROPERTIES_EXT)
            continue;
        const uint64_t partial[2] = {
            VK_MAX_MEMORY_TYPES,
            VK_MAX_MEMORY_HEAPS,
        };
        uint8_t reply[1024];
        struct wire_decoder dec_storage;
        struct wire_decoder *dec = &dec_storage;
        if (begin_output_struct_query(
                physical, VN_CMD_GET_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2,
                0, 0,
                VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2,
                out->sType, partial, sizeof(partial), reply, sizeof(reply),
                dec) < 0)
            continue;
        VkPhysicalDeviceMemoryBudgetPropertiesEXT *budget =
            (VkPhysicalDeviceMemoryBudgetPropertiesEXT *)out;
        DARRAY(budget->heapBudget, VK_MAX_MEMORY_HEAPS);
        DARRAY(budget->heapUsage, VK_MAX_MEMORY_HEAPS);
    }
}

VKAPI_ATTR void VKAPI_CALL
venus_real_GetPhysicalDeviceFormatProperties2(
    VkPhysicalDevice physical_device, VkFormat format,
    VkFormatProperties2 *properties)
{
    if (!physical_device || !properties)
        return;
    struct venus_physical_device_real *physical =
        (struct venus_physical_device_real *)physical_device;
    VkFormatProperties3 *properties3 = 0;
    for (VkBaseOutStructure *out = (VkBaseOutStructure *)properties->pNext;
         out; out = out->pNext) {
        if (out->sType == VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_3) {
            properties3 = (VkFormatProperties3 *)out;
            break;
        }
    }
    uint8_t reply[128];
    struct wire_decoder dec_storage;
    struct wire_decoder *dec = &dec_storage;
    if (begin_output_struct_query(
            physical, VN_CMD_GET_PHYSICAL_DEVICE_FORMAT_PROPERTIES_2,
            &format, sizeof(format), VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_2,
            properties3 ? properties3->sType : 0,
            0, 0, reply, sizeof(reply), dec) < 0) {
        memset(&properties->formatProperties, 0,
               sizeof(properties->formatProperties));
        return;
    }
    if (properties3) {
        D64(properties3->linearTilingFeatures);
        D64(properties3->optimalTilingFeatures);
        D64(properties3->bufferFeatures);
    }
    D32(properties->formatProperties.linearTilingFeatures);
    D32(properties->formatProperties.optimalTilingFeatures);
    D32(properties->formatProperties.bufferFeatures);
    if (dec->failed) {
        memset(&properties->formatProperties, 0,
               sizeof(properties->formatProperties));
        if (properties3) {
            properties3->linearTilingFeatures = 0;
            properties3->optimalTilingFeatures = 0;
            properties3->bufferFeatures = 0;
        }
    }
}

static const VkBaseInStructure *
image_format_info_next_supported(const VkBaseInStructure *next)
{
    for (; next; next = next->pNext) {
        switch (next->sType) {
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO:
        case VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO:
        case VK_STRUCTURE_TYPE_IMAGE_STENCIL_USAGE_CREATE_INFO:
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_DRM_FORMAT_MODIFIER_INFO_EXT:
        case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_VIEW_IMAGE_FORMAT_INFO_EXT:
            return next;
        default:
            break;
        }
    }
    return 0;
}

static uint64_t
image_format_info_pnext_size(const VkBaseInStructure *next, int *valid)
{
    next = image_format_info_next_supported(next);
    if (!next)
        return 8;

    uint64_t self_size = 0;
    switch (next->sType) {
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO:
    case VK_STRUCTURE_TYPE_IMAGE_STENCIL_USAGE_CREATE_INFO:
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_VIEW_IMAGE_FORMAT_INFO_EXT:
        self_size = 4;
        break;
    case VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO: {
        const VkImageFormatListCreateInfo *list =
            (const VkImageFormatListCreateInfo *)next;
        if (list->viewFormatCount && !list->pViewFormats) {
            *valid = 0;
            return 0;
        }
        self_size = 12u + (uint64_t)list->viewFormatCount * 4u;
        break;
    }
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_DRM_FORMAT_MODIFIER_INFO_EXT: {
        const VkPhysicalDeviceImageDrmFormatModifierInfoEXT *modifier =
            (const VkPhysicalDeviceImageDrmFormatModifierInfoEXT *)next;
        if (modifier->sharingMode == VK_SHARING_MODE_CONCURRENT &&
            modifier->queueFamilyIndexCount &&
            !modifier->pQueueFamilyIndices) {
            *valid = 0;
            return 0;
        }
        self_size = 24u;
        if (modifier->sharingMode == VK_SHARING_MODE_CONCURRENT)
            self_size += (uint64_t)modifier->queueFamilyIndexCount * 4u;
        break;
    }
    default:
        *valid = 0;
        return 0;
    }

    uint64_t child_size = image_format_info_pnext_size(next->pNext, valid);
    if (!*valid || child_size > UINT32_MAX - 12u - self_size) {
        *valid = 0;
        return 0;
    }
    return 12u + child_size + self_size;
}

static void
encode_image_format_info_pnext(struct wire_encoder *enc,
                               const VkBaseInStructure *next)
{
    next = image_format_info_next_supported(next);
    if (!next) {
        encode_u64(enc, 0);
        return;
    }

    encode_u64(enc, 1);
    encode_u32(enc, (uint32_t)next->sType);
    encode_image_format_info_pnext(enc, next->pNext);
    switch (next->sType) {
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO: {
        const VkPhysicalDeviceExternalImageFormatInfo *external =
            (const VkPhysicalDeviceExternalImageFormatInfo *)next;
        encode_u32(enc, (uint32_t)external->handleType);
        break;
    }
    case VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO: {
        const VkImageFormatListCreateInfo *list =
            (const VkImageFormatListCreateInfo *)next;
        encode_u32(enc, list->viewFormatCount);
        encode_u64(enc, list->viewFormatCount);
        for (uint32_t i = 0; i < list->viewFormatCount; i++)
            encode_u32(enc, (uint32_t)list->pViewFormats[i]);
        break;
    }
    case VK_STRUCTURE_TYPE_IMAGE_STENCIL_USAGE_CREATE_INFO: {
        const VkImageStencilUsageCreateInfo *stencil =
            (const VkImageStencilUsageCreateInfo *)next;
        encode_u32(enc, stencil->stencilUsage);
        break;
    }
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_DRM_FORMAT_MODIFIER_INFO_EXT: {
        const VkPhysicalDeviceImageDrmFormatModifierInfoEXT *modifier =
            (const VkPhysicalDeviceImageDrmFormatModifierInfoEXT *)next;
        encode_u64(enc, modifier->drmFormatModifier);
        encode_u32(enc, (uint32_t)modifier->sharingMode);
        encode_u32(enc, modifier->queueFamilyIndexCount);
        uint64_t family_count = modifier->sharingMode ==
                VK_SHARING_MODE_CONCURRENT
            ? modifier->queueFamilyIndexCount : 0;
        encode_u64(enc, family_count);
        for (uint32_t i = 0; i < family_count; i++)
            encode_u32(enc, modifier->pQueueFamilyIndices[i]);
        break;
    }
    case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_VIEW_IMAGE_FORMAT_INFO_EXT: {
        const VkPhysicalDeviceImageViewImageFormatInfoEXT *view =
            (const VkPhysicalDeviceImageViewImageFormatInfoEXT *)next;
        encode_u32(enc, (uint32_t)view->imageViewType);
        break;
    }
    default:
        enc->failed = 1;
        break;
    }
}

static VkBaseOutStructure *
image_format_properties_next_supported(VkBaseOutStructure *next)
{
    for (; next; next = next->pNext) {
        switch (next->sType) {
        case VK_STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES:
        case VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES:
        case VK_STRUCTURE_TYPE_HOST_IMAGE_COPY_DEVICE_PERFORMANCE_QUERY:
        case VK_STRUCTURE_TYPE_FILTER_CUBIC_IMAGE_VIEW_IMAGE_FORMAT_PROPERTIES_EXT:
            return next;
        default:
            break;
        }
    }
    return 0;
}

static uint64_t
image_format_properties_pnext_size(VkBaseOutStructure *next, int partial)
{
    next = image_format_properties_next_supported(next);
    if (!next)
        return 8;

    uint64_t self_size = 0;
    if (!partial) {
        switch (next->sType) {
        case VK_STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES:
            self_size = 12;
            break;
        case VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES:
            self_size = 4;
            break;
        case VK_STRUCTURE_TYPE_HOST_IMAGE_COPY_DEVICE_PERFORMANCE_QUERY:
        case VK_STRUCTURE_TYPE_FILTER_CUBIC_IMAGE_VIEW_IMAGE_FORMAT_PROPERTIES_EXT:
            self_size = 8;
            break;
        default:
            break;
        }
    }
    return 12u + image_format_properties_pnext_size(next->pNext, partial) +
           self_size;
}

static void
encode_image_format_properties_pnext_partial(struct wire_encoder *enc,
                                             VkBaseOutStructure *next)
{
    next = image_format_properties_next_supported(next);
    if (!next) {
        encode_u64(enc, 0);
        return;
    }
    encode_u64(enc, 1);
    encode_u32(enc, (uint32_t)next->sType);
    encode_image_format_properties_pnext_partial(enc, next->pNext);
}

static VkBaseOutStructure *
find_image_format_property(VkBaseOutStructure *next, uint32_t s_type)
{
    for (; next; next = next->pNext) {
        if ((uint32_t)next->sType == s_type)
            return next;
    }
    return 0;
}

static void
decode_image_format_properties_pnext(struct wire_decoder *dec,
                                     VkBaseOutStructure *next)
{
    uint64_t present = 0;
    D64(present);
    if (dec->failed || !present)
        return;

    uint32_t s_type = 0;
    D32(s_type);
    VkBaseOutStructure *property =
        find_image_format_property(next, s_type);
    if (!property) {
        dec->failed = 1;
        return;
    }

    decode_image_format_properties_pnext(dec, property->pNext);
    switch (property->sType) {
    case VK_STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES: {
        VkExternalImageFormatProperties *external =
            (VkExternalImageFormatProperties *)property;
        D32(external->externalMemoryProperties.externalMemoryFeatures);
        D32(external->externalMemoryProperties.exportFromImportedHandleTypes);
        D32(external->externalMemoryProperties.compatibleHandleTypes);
        break;
    }
    case VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES: {
        VkSamplerYcbcrConversionImageFormatProperties *ycbcr =
            (VkSamplerYcbcrConversionImageFormatProperties *)property;
        D32(ycbcr->combinedImageSamplerDescriptorCount);
        break;
    }
    case VK_STRUCTURE_TYPE_HOST_IMAGE_COPY_DEVICE_PERFORMANCE_QUERY: {
        VkHostImageCopyDevicePerformanceQuery *performance =
            (VkHostImageCopyDevicePerformanceQuery *)property;
        D32(performance->optimalDeviceAccess);
        D32(performance->identicalMemoryLayout);
        break;
    }
    case VK_STRUCTURE_TYPE_FILTER_CUBIC_IMAGE_VIEW_IMAGE_FORMAT_PROPERTIES_EXT: {
        VkFilterCubicImageViewImageFormatPropertiesEXT *cubic =
            (VkFilterCubicImageViewImageFormatPropertiesEXT *)property;
        D32(cubic->filterCubic);
        D32(cubic->filterCubicMinmax);
        break;
    }
    default:
        dec->failed = 1;
        break;
    }
}

VKAPI_ATTR VkResult VKAPI_CALL
venus_real_GetPhysicalDeviceImageFormatProperties2(
    VkPhysicalDevice physical_device,
    const VkPhysicalDeviceImageFormatInfo2 *info,
    VkImageFormatProperties2 *properties)
{
    if (!physical_device || !info || !properties ||
        info->sType != VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2 ||
        properties->sType != VK_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2)
        return VK_ERROR_INITIALIZATION_FAILED;
    int valid = 1;
    uint64_t info_chain_size = image_format_info_pnext_size(
        (const VkBaseInStructure *)info->pNext, &valid);
    uint64_t property_chain_partial_size =
        image_format_properties_pnext_size(
            (VkBaseOutStructure *)properties->pNext, 1);
    uint64_t property_chain_reply_size =
        image_format_properties_pnext_size(
            (VkBaseOutStructure *)properties->pNext, 0);
    uint64_t command_size64 = 60u + info_chain_size +
                              property_chain_partial_size;
    uint64_t reply_size64 = 52u + property_chain_reply_size;
    if (!valid || command_size64 > UINT32_MAX ||
        reply_size64 > UINT32_MAX || reply_size64 > 65536u)
        return VK_ERROR_OUT_OF_HOST_MEMORY;

    uint32_t command_size = (uint32_t)command_size64;
    uint32_t reply_size = (uint32_t)reply_size64;
    uint8_t *command = malloc(command_size);
    uint8_t *reply = malloc(reply_size);
    if (!command || !reply) {
        free(command);
        free(reply);
        return VK_ERROR_OUT_OF_HOST_MEMORY;
    }
    struct venus_physical_device_real *physical =
        (struct venus_physical_device_real *)physical_device;
    struct wire_encoder enc = {
        .data = command,
        .capacity = command_size,
    };
    encode_u32(&enc, VN_CMD_GET_PHYSICAL_DEVICE_IMAGE_FORMAT_PROPERTIES_2);
    encode_u32(&enc, VN_COMMAND_GENERATE_REPLY);
    encode_u64(&enc, physical->object_id);
    encode_u64(&enc, 1); /* pImageFormatInfo */
    encode_u32(&enc, (uint32_t)info->sType);
    encode_image_format_info_pnext(
        &enc, (const VkBaseInStructure *)info->pNext);
    encode_u32(&enc, (uint32_t)info->format);
    encode_u32(&enc, (uint32_t)info->type);
    encode_u32(&enc, (uint32_t)info->tiling);
    encode_u32(&enc, info->usage);
    encode_u32(&enc, info->flags);
    encode_u64(&enc, 1); /* pImageFormatProperties */
    encode_u32(&enc, (uint32_t)properties->sType);
    encode_image_format_properties_pnext_partial(
        &enc, (VkBaseOutStructure *)properties->pNext);
    if (enc.failed || enc.offset != command_size) {
        free(command);
        free(reply);
        return VK_ERROR_OUT_OF_HOST_MEMORY;
    }

    memset(reply, 0, reply_size);
    int wire_result = venus_wire_call(physical->instance->wire,
                                      command, command_size,
                                      reply, reply_size);
    free(command);
    if (wire_result < 0) {
        free(reply);
        return VK_ERROR_DEVICE_LOST;
    }
    struct wire_decoder dec_storage = {
        .data = reply,
        .capacity = reply_size,
    };
    struct wire_decoder *dec = &dec_storage;
    uint32_t returned_command = 0;
    int32_t result = VK_ERROR_DEVICE_LOST;
    uint64_t present = 0;
    uint32_t returned_type = 0;
    D32(returned_command);
    D32(result);
    D64(present);
    D32(returned_type);
    if (returned_command !=
            VN_CMD_GET_PHYSICAL_DEVICE_IMAGE_FORMAT_PROPERTIES_2 ||
        !present || returned_type != (uint32_t)properties->sType)
        dec->failed = 1;
    decode_image_format_properties_pnext(
        dec, (VkBaseOutStructure *)properties->pNext);
    D32(properties->imageFormatProperties.maxExtent.width);
    D32(properties->imageFormatProperties.maxExtent.height);
    D32(properties->imageFormatProperties.maxExtent.depth);
    D32(properties->imageFormatProperties.maxMipLevels);
    D32(properties->imageFormatProperties.maxArrayLayers);
    D32(properties->imageFormatProperties.sampleCounts);
    D64(properties->imageFormatProperties.maxResourceSize);
    if (dec->offset != reply_size)
        dec->failed = 1;
    int failed = dec->failed;
    free(reply);
    return failed ? VK_ERROR_DEVICE_LOST : (VkResult)result;
}

#undef DECODE_BOOL_RANGE

static VkResult get_host_device_extensions(
    struct venus_physical_device_real *physical, uint32_t *count,
    VkExtensionProperties *properties)
{
    uint32_t capacity = properties ? *count : 0;
    uint32_t reply_size = 28u + capacity *
        (8u + VK_MAX_EXTENSION_NAME_SIZE + 4u);
    if (reply_size > 65536u)
        return VK_ERROR_OUT_OF_HOST_MEMORY;
    uint8_t *reply = malloc(reply_size);
    if (!reply)
        return VK_ERROR_OUT_OF_HOST_MEMORY;

    uint8_t command[44];
    uint32_t command_type = VN_CMD_ENUMERATE_DEVICE_EXTENSION_PROPERTIES;
    uint32_t command_flags = VN_COMMAND_GENERATE_REPLY;
    uint64_t no_layer = 0;
    uint64_t count_present = 1;
    uint64_t array_size = capacity;
    memcpy(command, &command_type, 4);
    memcpy(command + 4, &command_flags, 4);
    memcpy(command + 8, &physical->object_id, 8);
    memcpy(command + 16, &no_layer, 8);
    memcpy(command + 24, &count_present, 8);
    memcpy(command + 32, &capacity, 4);
    memcpy(command + 36, &array_size, 8);

    memset(reply, 0, reply_size);
    if (venus_wire_call(physical->instance->wire, command, sizeof(command),
                        reply, reply_size) < 0) {
        free(reply);
        return VK_ERROR_DEVICE_LOST;
    }

    struct wire_decoder dec_storage = {
        .data = reply,
        .capacity = reply_size,
    };
    struct wire_decoder *dec = &dec_storage;
    uint32_t returned_command = 0;
    int32_t result = VK_ERROR_DEVICE_LOST;
    uint64_t returned_count_present = 0;
    uint32_t returned_count = 0;
    uint64_t returned_array_size = 0;
    D32(returned_command);
    D32(result);
    D64(returned_count_present);
    D32(returned_count);
    decode_bytes(dec, &returned_array_size, sizeof(returned_array_size));
    if (returned_command != VN_CMD_ENUMERATE_DEVICE_EXTENSION_PROPERTIES ||
        !returned_count_present || returned_array_size > capacity ||
        returned_array_size != (properties ? returned_count : 0))
        dec->failed = 1;
    for (uint32_t i = 0; i < returned_array_size && !dec->failed; i++) {
        if (decode_array_size(dec, VK_MAX_EXTENSION_NAME_SIZE) ==
            VK_MAX_EXTENSION_NAME_SIZE)
            decode_bytes(dec, properties[i].extensionName,
                         VK_MAX_EXTENSION_NAME_SIZE);
        D32(properties[i].specVersion);
    }
    free(reply);
    if (dec->failed)
        return VK_ERROR_DEVICE_LOST;
    *count = returned_count;
    return (VkResult)result;
}

static VkResult init_device_extensions(
    struct venus_physical_device_real *physical)
{
    if (physical->extensions_initialized)
        return VK_SUCCESS;
    uint32_t count = 0;
    VkResult result = get_host_device_extensions(physical, &count, 0);
    if (result != VK_SUCCESS)
        return result;
    if (!count) {
        physical->extensions_initialized = 1;
        return VK_SUCCESS;
    }
    VkExtensionProperties *properties =
        malloc((unsigned long)(count + 1u) * sizeof(*properties));
    if (!properties)
        return VK_ERROR_OUT_OF_HOST_MEMORY;
    memset(properties, 0, (unsigned long)count * sizeof(*properties));
    uint32_t returned_count = count;
    result = get_host_device_extensions(physical, &returned_count, properties);
    if (result != VK_SUCCESS || returned_count > count) {
        free(properties);
        return result == VK_SUCCESS ? VK_ERROR_DEVICE_LOST : result;
    }

    /* The host renderer can expose extensions newer than the guest Venus
     * transport.  Publish an extension only when this ICD can marshal its
     * complete command set; otherwise callers will enable it and receive
     * NULL device entrypoints.  VK_EXT_host_image_copy currently has no
     * guest protocol implementation (CopyMemoryToImageEXT,
     * CopyImageToMemoryEXT, CopyImageToImageEXT,
     * TransitionImageLayoutEXT, or GetImageSubresourceLayout2EXT). */
    uint32_t supported_count = 0;
    for (uint32_t i = 0; i < returned_count; i++) {
        if (strcmp(properties[i].extensionName,
                   VK_EXT_HOST_IMAGE_COPY_EXTENSION_NAME) == 0)
            continue;
        if (supported_count != i)
            properties[supported_count] = properties[i];
        supported_count++;
    }
    returned_count = supported_count;

    int has_swapchain = 0;
    for (uint32_t i = 0; i < returned_count; i++) {
        if (strcmp(properties[i].extensionName,
                   VK_KHR_SWAPCHAIN_EXTENSION_NAME) == 0) {
            has_swapchain = 1;
            break;
        }
    }
    if (!has_swapchain) {
        VkExtensionProperties *extension = &properties[returned_count++];
        memset(extension, 0, sizeof(*extension));
        const char name[] = VK_KHR_SWAPCHAIN_EXTENSION_NAME;
        memcpy(extension->extensionName, name, sizeof(name));
        extension->specVersion = VK_KHR_SWAPCHAIN_SPEC_VERSION;
    }
    physical->extension_properties = properties;
    physical->extension_count = returned_count;
    physical->extensions_initialized = 1;
    return VK_SUCCESS;
}

VKAPI_ATTR VkResult VKAPI_CALL
venus_real_EnumerateDeviceExtensionProperties(
    VkPhysicalDevice physical_device, const char *layer_name,
    uint32_t *property_count, VkExtensionProperties *properties)
{
    if (!physical_device || !property_count)
        return VK_ERROR_INITIALIZATION_FAILED;
    if (layer_name)
        return VK_ERROR_LAYER_NOT_PRESENT;
    struct venus_physical_device_real *physical =
        (struct venus_physical_device_real *)physical_device;
    VkResult result = init_device_extensions(physical);
    if (result != VK_SUCCESS)
        return result;
    if (!properties) {
        *property_count = physical->extension_count;
        return VK_SUCCESS;
    }
    uint32_t written = *property_count < physical->extension_count
        ? *property_count : physical->extension_count;
    memcpy(properties, physical->extension_properties,
           (unsigned long)written * sizeof(*properties));
    *property_count = written;
    return written < physical->extension_count ? VK_INCOMPLETE : VK_SUCCESS;
}

VKAPI_ATTR VkResult VKAPI_CALL
venus_real_GetPhysicalDeviceCalibrateableTimeDomainsEXT(
    VkPhysicalDevice physical_device, uint32_t *time_domain_count,
    VkTimeDomainKHR *time_domains)
{
    if (!physical_device || !time_domain_count)
        return VK_ERROR_INITIALIZATION_FAILED;

    struct venus_physical_device_real *physical =
        (struct venus_physical_device_real *)physical_device;
    uint32_t capacity = time_domains ? *time_domain_count : 0;
    uint64_t reply_size_64 = 28u + (uint64_t)capacity * 4u;
    if (reply_size_64 > 65536u)
        return VK_ERROR_OUT_OF_HOST_MEMORY;
    uint32_t reply_size = (uint32_t)reply_size_64;
    uint8_t *reply = malloc(reply_size);
    if (!reply)
        return VK_ERROR_OUT_OF_HOST_MEMORY;

    uint8_t command[36];
    struct wire_encoder enc = {
        .data = command,
        .capacity = sizeof(command),
    };
    encode_u32(&enc,
        VN_CMD_GET_PHYSICAL_DEVICE_CALIBRATEABLE_TIME_DOMAINS_EXT);
    encode_u32(&enc, VN_COMMAND_GENERATE_REPLY);
    encode_u64(&enc, physical->object_id);
    encode_u64(&enc, 1); /* pTimeDomainCount */
    encode_u32(&enc, capacity);
    encode_u64(&enc, time_domains ? capacity : 0);
    if (enc.failed) {
        free(reply);
        return VK_ERROR_INITIALIZATION_FAILED;
    }

    memset(reply, 0, reply_size);
    if (venus_wire_call(physical->instance->wire, command, sizeof(command),
                        reply, reply_size) < 0) {
        free(reply);
        return VK_ERROR_DEVICE_LOST;
    }

    struct wire_decoder dec_storage = {
        .data = reply,
        .capacity = reply_size,
    };
    struct wire_decoder *dec = &dec_storage;
    uint32_t returned_command = 0;
    int32_t result = VK_ERROR_DEVICE_LOST;
    uint64_t count_present = 0;
    uint32_t returned_count = 0;
    uint64_t array_size = 0;
    D32(returned_command);
    D32(result);
    D64(count_present);
    D32(returned_count);
    D64(array_size);
    if (returned_command !=
            VN_CMD_GET_PHYSICAL_DEVICE_CALIBRATEABLE_TIME_DOMAINS_EXT ||
        !count_present || array_size > capacity ||
        array_size != (time_domains ? returned_count : 0))
        dec->failed = 1;
    for (uint32_t i = 0; i < array_size && !dec->failed; i++)
        D32(time_domains[i]);

    free(reply);
    if (dec->failed)
        return VK_ERROR_DEVICE_LOST;
    *time_domain_count = returned_count;
    return (VkResult)result;
}

#undef DARRAY
#undef D64
#undef D32
